import assert from 'node:assert/strict'
import { describe, it } from 'node:test'

import { oracle } from '../../../dialects/oracle.ts'
import type {
  Column,
  ColumnType,
  Schema,
  Table,
  UserType,
} from '../../../schema/types.ts'

const dialect = oracle()
const varchar36 = oracle({ uuid: 'varchar36' })

describe('oracle: names', () => {
  it('upper-cases a plain name and leaves it unquoted', () => {
    assert.equal(dialect.quoteIdentifier('users'), 'USERS')
    assert.equal(dialect.quoteIdentifier('Created_At'), 'CREATED_AT')
    assert.equal(dialect.quoteIdentifier('a$b#c'), 'A$B#C')
  })

  it('quotes a reserved word, in any case, with the exact text', () => {
    assert.equal(dialect.quoteIdentifier('order'), '"order"')
    assert.equal(dialect.quoteIdentifier('User'), '"User"')
    assert.equal(dialect.quoteIdentifier('comment'), '"comment"')
    assert.equal(dialect.quoteIdentifier('date'), '"date"')
  })

  it('quotes a name with accents, spaces, hyphens, quotes, or that starts with a digit or an underscore', () => {
    assert.equal(dialect.quoteIdentifier('café'), '"café"')
    assert.equal(dialect.quoteIdentifier('my table'), '"my table"')
    assert.equal(dialect.quoteIdentifier('a-b'), '"a-b"')
    assert.equal(dialect.quoteIdentifier('1abc'), '"1abc"')
    assert.equal(dialect.quoteIdentifier('_x'), '"_x"')
    assert.equal(dialect.quoteIdentifier('say "hi"'), '"say ""hi"""')
  })

  it('names generated constraints in upper case', () => {
    assert.equal(dialect.constraintName('pk', ['users']), 'PK_USERS')
    assert.equal(
      dialect.constraintName('fk', ['orders', 'user_id']),
      'FK_ORDERS_USER_ID'
    )
    assert.equal(
      dialect.constraintName('ck', ['orders', 'active']),
      'CK_ORDERS_ACTIVE'
    )
  })

  it('allows 128 bytes, has no user types, and quotes literals', () => {
    assert.equal(dialect.maxIdentifierBytes, 128)
    assert.equal(dialect.supportsUserTypes, false)
    assert.equal(dialect.quoteLiteral("it's"), "'it''s'")
  })
})

describe('oracle: types', () => {
  const names: [ColumnType, string][] = [
    [{ kind: 'integer' }, 'NUMBER(10)'],
    [{ kind: 'bigint' }, 'NUMBER(19)'],
    [{ kind: 'smallint' }, 'NUMBER(5)'],
    [{ kind: 'numeric', precision: 12, scale: 2 }, 'NUMBER(12,2)'],
    [{ kind: 'varchar', length: 255 }, 'VARCHAR2(255)'],
    [{ kind: 'char', length: 2 }, 'CHAR(2)'],
    [{ kind: 'text' }, 'CLOB'],
    [{ kind: 'boolean' }, 'NUMBER(1)'],
    [{ kind: 'uuid' }, 'RAW(16)'],
    [{ kind: 'timestamp' }, 'TIMESTAMP WITH TIME ZONE'],
    [{ kind: 'timestamp_no_tz' }, 'TIMESTAMP'],
    [{ kind: 'date' }, 'DATE'],
    [{ kind: 'time' }, 'INTERVAL DAY(0) TO SECOND(0)'],
    [{ kind: 'interval' }, 'INTERVAL DAY TO SECOND'],
    [{ kind: 'json' }, 'CLOB'],
    [{ kind: 'real' }, 'BINARY_FLOAT'],
    [{ kind: 'double' }, 'BINARY_DOUBLE'],
    [{ kind: 'bytea' }, 'BLOB'],
    [{ kind: 'array', of: { kind: 'integer' } }, 'CLOB'],
  ]
  for (const [type, expected] of names) {
    it(`writes ${type.kind} as ${expected}`, () =>
      assert.equal(dialect.typeName(type), expected))
  }

  it('writes a uuid as VARCHAR2(36) when asked', () => {
    assert.equal(varchar36.typeName({ kind: 'uuid' }), 'VARCHAR2(36)')
  })
})

describe('oracle: generated columns', () => {
  it('uses an identity for integers, SYS_GUID for a uuid, SYSTIMESTAMP for an instant', () => {
    assert.equal(
      dialect.generatedClause({ kind: 'integer' }),
      'GENERATED BY DEFAULT ON NULL AS IDENTITY'
    )
    assert.equal(
      dialect.generatedClause({ kind: 'bigint' }),
      'GENERATED BY DEFAULT ON NULL AS IDENTITY'
    )
    assert.equal(
      dialect.generatedClause({ kind: 'uuid' }),
      'DEFAULT SYS_GUID()'
    )
    assert.equal(
      dialect.generatedClause({ kind: 'timestamp' }),
      'DEFAULT SYSTIMESTAMP'
    )
    assert.equal(dialect.generatedClause({ kind: 'text' }), null)
  })

  it('hyphenates the guid when the uuid is a VARCHAR2(36)', () => {
    assert.equal(
      varchar36.generatedClause({ kind: 'uuid' }),
      "DEFAULT LOWER(REGEXP_REPLACE(RAWTOHEX(SYS_GUID()), '([A-F0-9]{8})([A-F0-9]{4})([A-F0-9]{4})([A-F0-9]{4})([A-F0-9]{12})', '\\1-\\2-\\3-\\4-\\5'))"
    )
  })

  it('says only an integer identity implies NOT NULL', () => {
    assert.equal(dialect.generatedImpliesNotNull({ kind: 'integer' }), true)
    assert.equal(dialect.generatedImpliesNotNull({ kind: 'uuid' }), false)
    assert.equal(dialect.generatedImpliesNotNull({ kind: 'timestamp' }), false)
  })
})

const col = (
  id: string,
  name: string,
  type: ColumnType,
  extra: Partial<Column> = {}
): Column => ({
  id,
  name,
  type,
  nullable: true,
  ...extra,
})
const tbl = (
  id: string,
  name: string,
  columns: Column[],
  extra: Partial<Table> = {}
): Table => ({
  id,
  name,
  columns,
  primaryKey: [],
  ...extra,
})
const schemaOf = (tables: Table[], types?: UserType[]): Schema => ({
  version: 1,
  tables,
  relationships: [],
  ...(types ? { types } : {}),
})
const parts = (schema: Schema, tableId: string, d = dialect) => {
  const notes: import('../../../dialects/dialect.ts').DialectNote[] = []
  const table = schema.tables.find((t) => t.id === tableId) as Table
  return {
    ...d.tableParts({ schema, table, notes, usedNames: new Set() }),
    notes,
  }
}

describe('oracle: a table', () => {
  it('writes DEFAULT before NOT NULL, and no NOT NULL for a primary key or an identity', () => {
    const schema = schemaOf([
      tbl(
        't',
        'jobs',
        [
          col(
            'a',
            'id',
            { kind: 'integer' },
            { nullable: false, generated: true }
          ),
          col(
            'b',
            'code',
            { kind: 'varchar', length: 10 },
            { nullable: false, default: "'X'" }
          ),
          col(
            'c',
            'created_at',
            { kind: 'timestamp' },
            { nullable: false, generated: true }
          ),
          col('d', 'key', { kind: 'uuid' }, { nullable: false }),
        ],
        { primaryKey: ['d'] }
      ),
    ])
    assert.deepEqual(parts(schema, 't').columns, [
      '  ID NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY',
      "  CODE VARCHAR2(10) DEFAULT 'X' NOT NULL",
      '  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL',
      '  KEY RAW(16)',
    ])
  })

  it('names the primary key PK_<TABLE>', () => {
    const schema = schemaOf([
      tbl(
        't',
        'jobs',
        [
          col('a', 'id', { kind: 'integer' }),
          col('b', 'tenant', { kind: 'integer' }),
        ],
        { primaryKey: ['a', 'b'] }
      ),
    ])
    assert.deepEqual(parts(schema, 't').keys, [
      '  CONSTRAINT PK_JOBS PRIMARY KEY (ID, TENANT)',
    ])
  })

  it('adds the CHECK of a boolean, a json and an array, named CK_<TABLE>_<COLUMN>', () => {
    const schema = schemaOf([
      tbl('t', 'jobs', [
        col('a', 'active', { kind: 'boolean' }),
        col('b', 'config', { kind: 'json' }),
        col('c', 'tags', { kind: 'array', of: { kind: 'text' } }),
      ]),
    ])
    const result = parts(schema, 't')
    assert.deepEqual(result.checks, [
      '  CONSTRAINT CK_JOBS_ACTIVE CHECK (ACTIVE IN (0,1))',
      '  CONSTRAINT CK_JOBS_CONFIG CHECK (CONFIG IS JSON)',
      '  CONSTRAINT CK_JOBS_TAGS CHECK (TAGS IS JSON)',
    ])
    assert.deepEqual(
      result.notes.map((n) => [n.code, n.tableId, n.columnId]),
      [['array-as-json', 't', 'c']]
    )
  })

  it('folds an enum into VARCHAR2 and a CHECK, sized by its longest value', () => {
    const colour: UserType = {
      kind: 'enum',
      id: 'e',
      name: 'colour',
      values: ['red', "it's green"],
    }
    const schema = schemaOf(
      [tbl('t', 'paint', [col('a', 'tone', { kind: 'user', typeId: 'e' })])],
      [colour]
    )
    const result = parts(schema, 't')
    assert.deepEqual(result.columns, ['  TONE VARCHAR2(10)'])
    assert.deepEqual(result.checks, [
      "  CONSTRAINT CK_PAINT_TONE CHECK (TONE IN ('red', 'it''s green'))",
    ])
  })

  it('folds a domain into its base type, repeating its default and NOT NULL', () => {
    const email: UserType = {
      kind: 'domain',
      id: 'd',
      name: 'email',
      base: { kind: 'varchar', length: 255 },
      notNull: true,
      default: "'x@y'",
    }
    const schema = schemaOf(
      [
        tbl('t', 'people', [
          col('a', 'mail', { kind: 'user', typeId: 'd' }),
          col(
            'b',
            'other',
            { kind: 'user', typeId: 'd' },
            { default: "'o@y'" }
          ),
        ]),
      ],
      [email]
    )
    assert.deepEqual(parts(schema, 't').columns, [
      "  MAIL VARCHAR2(255) DEFAULT 'x@y' NOT NULL",
      "  OTHER VARCHAR2(255) DEFAULT 'o@y' NOT NULL",
    ])
  })

  it('notes a raw default, a long varchar and an over-precise numeric, and adapts them', () => {
    const schema = schemaOf([
      tbl('t', 'stuff', [
        col('a', 'created', { kind: 'timestamp' }, { default: 'now()' }),
        col('b', 'body', { kind: 'varchar', length: 5000 }),
        col('c', 'amount', { kind: 'numeric', precision: 50, scale: 4 }),
      ]),
    ])
    const result = parts(schema, 't')
    assert.deepEqual(result.columns, [
      '  CREATED TIMESTAMP WITH TIME ZONE DEFAULT now()',
      '  BODY CLOB',
      '  AMOUNT NUMBER(38,4)',
    ])
    assert.deepEqual(
      result.notes.map((n) => n.code),
      ['raw-default', 'text-too-long', 'numeric-precision']
    )
  })

  it('writes a uuid as VARCHAR2(36) with the hyphenated default when asked', () => {
    const schema = schemaOf([
      tbl('t', 'k', [col('a', 'id', { kind: 'uuid' }, { generated: true })]),
    ])
    assert.match(
      parts(schema, 't', varchar36).columns[0] ?? '',
      /^ {2}ID VARCHAR2\(36\) DEFAULT LOWER\(REGEXP_REPLACE\(RAWTOHEX\(SYS_GUID\(\)\)/
    )
  })
})

describe('oracle: indexes', () => {
  const schema = schemaOf([
    tbl(
      't',
      'users',
      [
        col('a', 'email', { kind: 'varchar', length: 100 }),
        col('b', 'bio', { kind: 'text' }),
      ],
      {
        indexes: [
          {
            id: 'i1',
            name: 'uq_users_email',
            columns: ['a'],
            unique: true,
            method: 'btree',
          },
          {
            id: 'i2',
            name: 'idx_users_email_gin',
            columns: ['a'],
            unique: false,
            method: 'gin',
          },
          {
            id: 'i3',
            name: 'idx_users_bio',
            columns: ['b'],
            unique: false,
            method: 'btree',
          },
        ],
      }
    ),
  ])
  const create = (id: string) => {
    const table = schema.tables[0] as Table
    const notes: import('../../../dialects/dialect.ts').DialectNote[] = []
    const index = table.indexes?.find((i) => i.id === id) as never
    return { sql: dialect.createIndex({ schema, table, index, notes }), notes }
  }

  it('writes a unique and a plain index', () => {
    assert.equal(
      create('i1').sql,
      'CREATE UNIQUE INDEX UQ_USERS_EMAIL ON USERS (EMAIL);'
    )
  })

  it('creates a hash, gin or gist index as an ordinary one, with a note', () => {
    const { sql, notes } = create('i2')
    assert.equal(sql, 'CREATE INDEX IDX_USERS_EMAIL_GIN ON USERS (EMAIL);')
    assert.deepEqual(
      notes.map((n) => [n.code, n.indexId]),
      [['index-method', 'i2']]
    )
  })

  it('does not create an index over a CLOB, and says so', () => {
    const { sql, notes } = create('i3')
    assert.equal(sql, null)
    assert.deepEqual(
      notes.map((n) => [n.code, n.indexId]),
      [['index-on-lob', 'i3']]
    )
  })
})

describe('oracle: what blocks', () => {
  const codes = (schema: Schema) =>
    dialect.check(schema).map((issue) => issue.code)

  it('accepts an ordinary schema', () => {
    assert.deepEqual(
      codes(
        schemaOf([
          tbl('t', 'users', [col('a', 'id', { kind: 'integer' })], {
            primaryKey: ['a'],
          }),
        ])
      ),
      []
    )
  })

  it('refuses a primary key, a unique index and a foreign key over a CLOB or BLOB', () => {
    const pk = schemaOf([
      tbl('t', 'a', [col('x', 'body', { kind: 'text' })], {
        primaryKey: ['x'],
      }),
    ])
    assert.deepEqual(codes(pk), ['dialect-lob-key'])
    const unique = schemaOf([
      tbl('t', 'a', [col('x', 'body', { kind: 'json' })], {
        indexes: [
          { id: 'i', name: 'u', columns: ['x'], unique: true, method: 'btree' },
        ],
      }),
    ])
    assert.deepEqual(codes(unique), ['dialect-lob-key'])
    const fk: Schema = {
      ...schemaOf([
        tbl('t1', 'a', [col('x', 'body', { kind: 'text' })], {
          primaryKey: [],
        }),
        tbl('t2', 'b', [col('y', 'ref', { kind: 'text' })]),
      ]),
      relationships: [
        {
          id: 'r',
          from: { tableId: 't2', columnId: 'y' },
          to: { tableId: 't1', columnId: 'x' },
        },
      ],
    }
    assert.ok(codes(fk).includes('dialect-lob-key'))
  })

  it('refuses names that are the same once folded to upper case, for tables and for columns', () => {
    assert.deepEqual(
      codes(schemaOf([tbl('1', 'users', []), tbl('2', 'Users', [])])),
      ['dialect-name-collision']
    )
    assert.deepEqual(
      codes(
        schemaOf([
          tbl('1', 't', [
            col('a', 'name', { kind: 'text' }),
            col('b', 'NAME', { kind: 'text' }),
          ]),
        ])
      ),
      ['dialect-name-collision']
    )
  })

  it('does not call a quoted reserved word and a plain name a collision', () => {
    assert.deepEqual(
      codes(schemaOf([tbl('1', 'order', []), tbl('2', 'orders', [])])),
      []
    )
  })

  it('refuses a name longer than 128 bytes', () => {
    assert.deepEqual(codes(schemaOf([tbl('1', 'x'.repeat(129), [])])), [
      'dialect-name-too-long',
    ])
    assert.deepEqual(
      codes(
        schemaOf([tbl('1', 't', [col('a', 'é'.repeat(65), { kind: 'text' })])])
      ),
      ['dialect-name-too-long']
    )
  })
})
