import assert from 'node:assert/strict'
import { describe, it } from 'node:test'

import { postgres } from '../../../dialects/postgres.ts'
import type { Schema } from '../../../schema/types.ts'
import { generateDdl } from '../../../sql/generate/generate-ddl.ts'

const schema: Schema = {
  version: 1,
  tables: [
    {
      id: 't1',
      name: 'users',
      columns: [
        {
          id: 'c1',
          name: 'id',
          type: { kind: 'integer' },
          nullable: false,
          generated: true,
        },
        { id: 'c2', name: 'bio', type: { kind: 'text' }, nullable: true },
      ],
      primaryKey: ['c1'],
      indexes: [
        {
          id: 'i1',
          name: 'idx_users_bio',
          columns: ['c2'],
          unique: false,
          method: 'gin',
        },
      ],
    },
  ],
  relationships: [],
}

describe('the PostgreSQL dialect on the hooks', () => {
  it('has the same identity, user types and constraint names as before', () => {
    assert.equal(postgres.id, 'postgres')
    assert.equal(postgres.supportsUserTypes, true)
    assert.equal(
      postgres.constraintName('fk', ['orders', 'user_id']),
      'fk_orders_user_id'
    )
    assert.deepEqual(postgres.check(schema), [])
  })

  it('writes the columns and an unnamed primary key, and no checks', () => {
    const parts = postgres.tableParts({
      schema,
      table: schema.tables[0] as never,
      notes: [],
      usedNames: new Set(),
    })
    assert.deepEqual(parts, {
      columns: [
        '  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY',
        '  "bio" text',
      ],
      keys: ['  PRIMARY KEY ("id")'],
      checks: [],
    })
  })

  it('writes an index with its method, and never skips one', () => {
    const table = schema.tables[0]
    assert.ok(table?.indexes?.[0])
    const sql = postgres.createIndex({
      schema,
      table,
      index: table.indexes[0],
      notes: [],
    })
    assert.equal(
      sql,
      'CREATE INDEX "idx_users_bio" ON "users" USING gin ("bio");'
    )
  })
})

describe('generateDdl with PostgreSQL', () => {
  it('returns no notes, and the script it always did', () => {
    const result = generateDdl(schema, postgres)
    assert.equal(result.ok, true)
    if (!result.ok) return
    assert.deepEqual(result.notes, [])
    assert.equal(
      result.sql,
      [
        'CREATE TABLE "users" (',
        '  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,',
        '  "bio" text,',
        '  PRIMARY KEY ("id")',
        ');',
        '',
        'CREATE INDEX "idx_users_bio" ON "users" USING gin ("bio");',
        '',
      ].join('\n')
    )
  })
})
