import assert from 'node:assert/strict'
import { describe, it } from 'node:test'

import { postgres } from '../../../dialects/postgres.ts'
import type { ColumnType } from '../../../schema/types.ts'

describe('postgres.typeName', () => {
  const cases: [ColumnType, string][] = [
    [{ kind: 'integer' }, 'integer'],
    [{ kind: 'bigint' }, 'bigint'],
    [{ kind: 'text' }, 'text'],
    [{ kind: 'boolean' }, 'boolean'],
    [{ kind: 'uuid' }, 'uuid'],
    [{ kind: 'date' }, 'date'],
    [{ kind: 'timestamp' }, 'timestamptz'],
    [{ kind: 'json' }, 'jsonb'],
    [{ kind: 'varchar', length: 120 }, 'varchar(120)'],
    [{ kind: 'numeric', precision: 10, scale: 2 }, 'numeric(10,2)'],
  ]

  for (const [type, expected] of cases) {
    it(`maps ${JSON.stringify(type)} to ${expected}`, () => {
      assert.equal(postgres.typeName(type), expected)
    })
  }
})

describe('postgres.quoteIdentifier', () => {
  it('wraps the name in double quotes', () => {
    assert.equal(postgres.quoteIdentifier('users'), '"users"')
  })

  it('preserves case and spaces', () => {
    assert.equal(postgres.quoteIdentifier('Order Items'), '"Order Items"')
  })

  it('escapes embedded double quotes by doubling them', () => {
    assert.equal(postgres.quoteIdentifier('a"b'), '"a""b"')
    assert.equal(postgres.quoteIdentifier('"'), '""""')
  })

  it('keeps non-ASCII characters', () => {
    assert.equal(postgres.quoteIdentifier('coluna_ção'), '"coluna_ção"')
  })
})

describe('postgres metadata', () => {
  it('declares its id and identifier limit', () => {
    assert.equal(postgres.id, 'postgres')
    assert.equal(postgres.maxIdentifierBytes, 63)
  })
})

describe('postgres.generatedClause', () => {
  it('uses an identity column for integer and bigint', () => {
    assert.equal(
      postgres.generatedClause({ kind: 'integer' }),
      'GENERATED BY DEFAULT AS IDENTITY'
    )
    assert.equal(
      postgres.generatedClause({ kind: 'bigint' }),
      'GENERATED BY DEFAULT AS IDENTITY'
    )
  })

  it('uses gen_random_uuid() as the default of a uuid', () => {
    assert.equal(
      postgres.generatedClause({ kind: 'uuid' }),
      'DEFAULT gen_random_uuid()'
    )
  })

  it('has nothing to generate for the other types', () => {
    assert.equal(postgres.generatedClause({ kind: 'text' }), null)
    assert.equal(postgres.generatedClause({ kind: 'varchar', length: 5 }), null)
  })
})

describe('postgres.generatedImpliesNotNull', () => {
  it('is true for the identity types: PostgreSQL makes them NOT NULL', () => {
    assert.equal(postgres.generatedImpliesNotNull({ kind: 'integer' }), true)
    assert.equal(postgres.generatedImpliesNotNull({ kind: 'bigint' }), true)
  })

  it('is false for a uuid default and for types that cannot be generated', () => {
    assert.equal(postgres.generatedImpliesNotNull({ kind: 'uuid' }), false)
    assert.equal(postgres.generatedImpliesNotNull({ kind: 'text' }), false)
  })
})
