import { mkdtempSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'

import type { Page } from '@playwright/test'
import { expect, test } from '@playwright/test'

import { Editor } from '../support/editor.ts'

const SHOP = `
CREATE TYPE order_status AS ENUM ('pending', 'paid');
CREATE TABLE users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar(255) NOT NULL UNIQUE,
  created_at timestamptz DEFAULT now() NOT NULL
);
CREATE TABLE orders (
  id integer PRIMARY KEY,
  user_id integer NOT NULL REFERENCES users (id),
  status order_status DEFAULT 'pending'
);
CREATE INDEX idx_orders_user ON orders (user_id);
COMMENT ON TABLE users IS 'People';
INSERT INTO users VALUES (1, 'a@b.c');
`

async function openImport(page: Page) {
  await page.setViewportSize({ width: 1400, height: 900 })
  const editor = new Editor(page)
  await editor.open()
  return editor
}

const dialog = (page: Page) => page.getByRole('dialog', { name: 'Import SQL' })
const sqlBox = (page: Page) => dialog(page).getByLabel('SQL', { exact: true })

test.describe('importing SQL', () => {
  test('pasting a script shows a preview with counts and a skipped statement with its line', async ({
    page,
  }) => {
    await openImport(page)
    await page.getByRole('button', { name: 'Import SQL' }).click()
    await sqlBox(page).fill(SHOP)

    const preview = dialog(page).getByRole('region', { name: 'Import preview' })
    await expect(preview).toContainText(
      'This script has 2 tables, 6 columns, 1 relationship, 2 indexes, 1 type.'
    )
    await expect(preview.getByRole('list', { name: 'Warnings' })).toContainText(
      'INSERT INTO statements are not modelled'
    )
    await expect(preview.getByRole('list', { name: 'Warnings' })).toContainText(
      'line 15'
    )
    await expect(
      dialog(page).getByRole('button', { name: 'Import', exact: true })
    ).toBeEnabled()
  })

  test('importing into an empty project creates the tables and the relationship, laid out by it', async ({
    page,
  }) => {
    const editor = await openImport(page)
    await page.getByRole('button', { name: 'Import SQL' }).click()
    await sqlBox(page).fill(SHOP)
    await dialog(page)
      .getByRole('button', { name: 'Import', exact: true })
      .click()

    await expect(page.locator('dialog.import-dialog')).toHaveCount(0)
    await expect(editor.tables()).toHaveCount(2)
    await expect(editor.edges()).toHaveCount(1)
    const left = async (name: string) =>
      (await editor.node(name).locator('.table-node').boundingBox())?.x ?? NaN
    expect(await left('users')).toBeLessThan(await left('orders'))

    const sql = await editor.ddl()
    expect(sql).toContain('CREATE TYPE "order_status" AS ENUM')
    expect(sql).toContain(
      '"id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY'
    )
    expect(sql).toContain('"created_at" timestamptz NOT NULL DEFAULT now()')
    expect(sql).toContain(`COMMENT ON TABLE "users" IS 'People';`)
  })

  test('a script with a syntax error cannot be imported, and the error says which line', async ({
    page,
  }) => {
    await openImport(page)
    await page.getByRole('button', { name: 'Import SQL' }).click()
    await sqlBox(page).fill('CREATE TABLE a (x int);\nCREATE TABLE b (y);')
    const preview = dialog(page).getByRole('region', { name: 'Import preview' })
    await expect(preview.getByRole('list', { name: 'Errors' })).toContainText(
      'line 2'
    )
    await expect(
      dialog(page).getByRole('button', { name: 'Import', exact: true })
    ).toBeDisabled()
  })

  test('a script with nothing to import cannot be imported', async ({
    page,
  }) => {
    await openImport(page)
    await page.getByRole('button', { name: 'Import SQL' }).click()
    await sqlBox(page).fill('SET search_path = public;')
    await expect(
      dialog(page).getByRole('button', { name: 'Import', exact: true })
    ).toBeDisabled()
  })

  test('a .sql file can be loaded, and its text appears in the box', async ({
    page,
  }) => {
    const editor = await openImport(page)
    const file = path.join(
      mkdtempSync(path.join(tmpdir(), 'forge-')),
      'schema.sql'
    )
    writeFileSync(file, 'CREATE TABLE from_file (id int PRIMARY KEY);')
    await page.getByRole('button', { name: 'Import SQL' }).click()
    await dialog(page).getByLabel('SQL file').setInputFiles(file)
    await expect(sqlBox(page)).toHaveValue(/from_file/)
    await expect(
      dialog(page).getByRole('region', { name: 'Import preview' })
    ).toContainText('1 table')
    await dialog(page)
      .getByRole('button', { name: 'Import', exact: true })
      .click()
    await expect(editor.node('from_file')).toBeVisible()
  })

  test('a file loaded after typing replaces the text in the box, and is what gets imported', async ({
    page,
  }) => {
    const editor = await openImport(page)
    const file = path.join(
      mkdtempSync(path.join(tmpdir(), 'forge-')),
      'schema.sql'
    )
    writeFileSync(file, 'CREATE TABLE from_file (id int PRIMARY KEY);')
    await page.getByRole('button', { name: 'Import SQL' }).click()
    await sqlBox(page).fill('CREATE TABLE typed (id int);')
    await dialog(page).getByLabel('SQL file').setInputFiles(file)
    await expect(sqlBox(page)).toHaveValue(/from_file/)
    await expect(
      dialog(page).getByRole('region', { name: 'Import preview' })
    ).toContainText('1 table')
    await dialog(page)
      .getByRole('button', { name: 'Import', exact: true })
      .click()
    await expect(editor.node('from_file')).toBeVisible()
    await expect(editor.tables()).toHaveCount(1)
  })

  test('closing the dialog, by Cancel or by importing, puts the focus back on the Import SQL button', async ({
    page,
  }) => {
    await openImport(page)
    const button = page.getByRole('button', { name: 'Import SQL' })
    await button.click()
    await dialog(page).getByRole('button', { name: 'Cancel' }).click()
    await expect(button).toBeFocused()

    await button.click()
    await sqlBox(page).fill('CREATE TABLE a (id int);')
    await dialog(page)
      .getByRole('button', { name: 'Import', exact: true })
      .click()
    await expect(button).toBeFocused()
  })

  test('Import stays disabled while the preview is catching up with the text', async ({
    page,
  }) => {
    await openImport(page)
    await page.getByRole('button', { name: 'Import SQL' }).click()
    await sqlBox(page).fill('CREATE TABLE a (id int);')
    // The first fill is still being parsed; a second edit must not be importable
    // until the preview shows it.
    await sqlBox(page).fill('CREATE TABLE b (y);')
    await expect(
      dialog(page)
        .getByRole('region', { name: 'Import preview' })
        .getByRole('list', { name: 'Errors' })
    ).toBeVisible()
    await expect(
      dialog(page).getByRole('button', { name: 'Import', exact: true })
    ).toBeDisabled()
  })

  test('a file over 1 MB is refused', async ({ page }) => {
    await openImport(page)
    const file = path.join(
      mkdtempSync(path.join(tmpdir(), 'forge-')),
      'big.sql'
    )
    writeFileSync(file, `-- ${'x'.repeat(1024 * 1024 + 10)}\n`)
    await page.getByRole('button', { name: 'Import SQL' }).click()
    await dialog(page).getByLabel('SQL file').setInputFiles(file)
    await expect(dialog(page).getByRole('alert')).toContainText('over 1 MB')
    await expect(
      dialog(page).getByRole('button', { name: 'Import', exact: true })
    ).toBeDisabled()
  })

  test('adding to a project keeps its tables, renames a collision and places the new ones to the right', async ({
    page,
  }) => {
    const editor = await openImport(page)
    await editor.defineTable('users', [
      { name: 'id', type: 'integer', primaryKey: true },
    ])
    // Where the table sits on the canvas (flow space, not screen space: the
    // import fits the view, so screen coordinates move).
    const before = await editor.position('users')

    await page.getByRole('button', { name: 'Import SQL' }).click()
    await sqlBox(page).fill(
      'CREATE TABLE users (id int PRIMARY KEY); CREATE TABLE items (id int);'
    )
    await expect(dialog(page).getByLabel('Add to the project')).toBeChecked()
    await dialog(page)
      .getByRole('button', { name: 'Import', exact: true })
      .click()

    await expect(editor.tables()).toHaveCount(3)
    await expect(editor.node('users_2')).toBeVisible()
    await expect(editor.node('items')).toBeVisible()
    const first =
      (await editor.node('users').locator('.table-node').boundingBox())?.x ??
      NaN
    const added =
      (await editor.node('items').locator('.table-node').boundingBox())?.x ??
      NaN
    expect(added).toBeGreaterThan(first)
    expect(await editor.position('users')).toBe(before)
  })

  test('replacing the project needs a second click, and then only the script remains', async ({
    page,
  }) => {
    const editor = await openImport(page)
    await editor.defineTable('mine', [{ name: 'id', type: 'integer' }])
    await page.getByRole('button', { name: 'Import SQL' }).click()
    await sqlBox(page).fill('CREATE TABLE only_this (id int);')
    await dialog(page).getByLabel('Replace the project').check()
    await dialog(page)
      .getByRole('button', { name: 'Replace the project with this script' })
      .click()
    await expect(dialog(page)).toBeVisible()
    await dialog(page)
      .getByRole('button', { name: 'Click again to replace the project' })
      .click()

    await expect(editor.tables()).toHaveCount(1)
    await expect(editor.node('only_this')).toBeVisible()
  })

  test('Cancel and Escape close the dialog and change nothing', async ({
    page,
  }) => {
    const editor = await openImport(page)
    await editor.addTable('kept')
    await page.getByRole('button', { name: 'Import SQL' }).click()
    await sqlBox(page).fill('CREATE TABLE nope (id int);')
    await dialog(page).getByRole('button', { name: 'Cancel' }).click()
    await expect(page.locator('dialog.import-dialog')).toHaveCount(0)
    await page.getByRole('button', { name: 'Import SQL' }).click()
    await page.keyboard.press('Escape')
    await expect(page.locator('dialog.import-dialog')).toHaveCount(0)
    await expect(editor.tables()).toHaveCount(1)
  })

  test('an imported project is saved: a reload shows it', async ({ page }) => {
    const editor = await openImport(page)
    await page.getByRole('button', { name: 'Import SQL' }).click()
    await sqlBox(page).fill('CREATE TABLE persisted (id int PRIMARY KEY);')
    await dialog(page)
      .getByRole('button', { name: 'Import', exact: true })
      .click()
    await expect(editor.node('persisted')).toBeVisible()
    await page.reload()
    await expect(editor.node('persisted')).toBeVisible()
  })

  test('hundreds of skipped statements stay readable: the list is capped', async ({
    page,
  }) => {
    await openImport(page)
    await page.getByRole('button', { name: 'Import SQL' }).click()
    const noise = Array.from(
      { length: 300 },
      (_, i) => `INSERT INTO t VALUES (${i});`
    ).join('\n')
    await sqlBox(page).fill(`CREATE TABLE t (id int);\n${noise}`)
    const warnings = dialog(page).getByRole('list', { name: 'Warnings' })
    await expect(warnings.locator('li')).toHaveCount(100)
    await expect(dialog(page)).toContainText('…and 200 more.')
  })

  test('identical errors on one line do not break the list', async ({
    page,
  }) => {
    await openImport(page)
    const problems: string[] = []
    page.on('console', (message) => {
      if (message.type() === 'error' || message.type() === 'warning') {
        problems.push(message.text())
      }
    })
    await page.getByRole('button', { name: 'Import SQL' }).click()
    await sqlBox(page).fill('CREATE TABLE b (y); CREATE TABLE b (y);')
    await expect(
      dialog(page).getByRole('list', { name: 'Errors' }).locator('li')
    ).toHaveCount(2)
    expect(
      problems.filter((text) => /same key|unique "key"/i.test(text))
    ).toEqual([])
  })

  test('a project that has only types still offers Add or Replace', async ({
    page,
  }) => {
    const editor = await openImport(page)
    await page.getByRole('button', { name: 'Add enum' }).click()
    await expect(editor.tables()).toHaveCount(0)
    await page.getByRole('button', { name: 'Import SQL' }).click()
    await sqlBox(page).fill("CREATE TYPE type_1 AS ENUM ('a');")
    await expect(dialog(page).getByLabel('Add to the project')).toBeVisible()
    await expect(dialog(page).getByLabel('Replace the project')).toBeVisible()
  })

  test('the same file can be loaded again after its text was changed', async ({
    page,
  }) => {
    await openImport(page)
    const file = path.join(
      mkdtempSync(path.join(tmpdir(), 'forge-')),
      'again.sql'
    )
    writeFileSync(file, 'CREATE TABLE again (id int);')
    await page.getByRole('button', { name: 'Import SQL' }).click()
    await dialog(page).getByLabel('SQL file').setInputFiles(file)
    await expect(sqlBox(page)).toHaveValue(/again/)
    await sqlBox(page).fill('')
    await expect(sqlBox(page)).toHaveValue('')
    writeFileSync(file, 'CREATE TABLE again (id int, more int);')
    await dialog(page).getByLabel('SQL file').setInputFiles(file)
    await expect(sqlBox(page)).toHaveValue(/more int/)
    // The input forgets its file once it was read, so choosing it again is a change.
    await expect(dialog(page).getByLabel('SQL file')).toHaveValue('')
  })
})
