import type { Page } from '@playwright/test'
import { expect, test } from '@playwright/test'

import { Editor } from '../support/editor.ts'

const newTable = (page: Page) =>
  page.getByRole('button', { name: 'New table' }).click()

const checkbox = (page: Page) =>
  page.getByLabel('created_at / updated_at on new tables')

test.describe('the timestamps of a new table', () => {
  test('are off by default', async ({ page }) => {
    const editor = new Editor(page)
    await editor.open({ newTableId: 'app-default' })
    await expect(checkbox(page)).not.toBeChecked()

    await newTable(page)
    await expect(editor.node('table_1')).not.toContainText('created_at')
  })

  test('once chosen, new tables get created_at and updated_at with DEFAULT now()', async ({
    page,
  }) => {
    const editor = new Editor(page)
    await editor.open({ newTableId: 'app-default' })
    await checkbox(page).check()

    await newTable(page)
    const node = editor.node('table_1')
    await expect(node.locator('.table-node__column')).toHaveCount(3)
    await expect(node).toContainText('created_at')
    await expect(node).toContainText('updated_at')

    expect(await editor.ddl()).toBe(
      'CREATE TABLE "table_1" (\n  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,\n  "created_at" timestamptz NOT NULL DEFAULT now(),\n  "updated_at" timestamptz NOT NULL DEFAULT now(),\n  PRIMARY KEY ("id")\n);\n'
    )
  })

  test('the choice survives a reload and applies only to tables created afterwards', async ({
    page,
  }) => {
    const editor = new Editor(page)
    await editor.open({ newTableId: 'app-default' })
    await newTable(page)
    await checkbox(page).check()
    await expect(editor.node('table_1')).not.toContainText('created_at')

    await page.reload()
    await expect(checkbox(page)).toBeChecked()
  })
})
