import type { Page } from '@playwright/test'
import { expect, test } from '@playwright/test'

import { Editor } from '../support/editor.ts'

const newTable = (page: Page) =>
  page.getByRole('button', { name: 'New table' }).click()

test.describe('the id of a new table', () => {
  test('a new table starts with a generated integer id by default', async ({
    page,
  }) => {
    const editor = new Editor(page)
    await editor.open({ newTableId: 'app-default' })
    await expect(editor.newTableIdSelect()).toHaveValue('integer')

    await newTable(page)
    const node = editor.node('table_1')
    await expect(node.locator('.table-node__column')).toHaveCount(1)
    await expect(node).toContainText('id')
    await expect(node).toContainText('integer')
    await expect(
      node.locator('.table-node__badge', { hasText: 'PK' })
    ).toBeVisible()
    await expect(
      node.locator('.table-node__badge', { hasText: 'auto' })
    ).toBeVisible()

    expect(await editor.ddl()).toBe(
      'CREATE TABLE "table_1" (\n  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,\n  PRIMARY KEY ("id")\n);\n'
    )
  })

  test('choosing uuid makes new tables start with a generated uuid id', async ({
    page,
  }) => {
    const editor = new Editor(page)
    await editor.open({ newTableId: 'app-default' })
    await editor.chooseNewTableId('uuid')
    await newTable(page)

    await expect(editor.node('table_1')).toContainText('uuid')
    expect(await editor.ddl()).toBe(
      'CREATE TABLE "table_1" (\n  "id" uuid NOT NULL DEFAULT gen_random_uuid(),\n  PRIMARY KEY ("id")\n);\n'
    )
  })

  test('choosing no id column starts new tables empty', async ({ page }) => {
    const editor = new Editor(page)
    await editor.open({ newTableId: 'app-default' })
    await editor.chooseNewTableId('none')
    await newTable(page)

    await expect(
      editor.node('table_1').locator('.table-node__column')
    ).toHaveCount(0)
    expect(await editor.ddl()).toBe('CREATE TABLE "table_1" ();\n')
  })

  test('changing the choice leaves the tables that already exist alone', async ({
    page,
  }) => {
    const editor = new Editor(page)
    await editor.open({ newTableId: 'app-default' })
    await newTable(page)
    await editor.chooseNewTableId('uuid')
    await newTable(page)

    await expect(editor.node('table_1')).toContainText('integer')
    await expect(editor.node('table_2')).toContainText('uuid')
  })

  test('the choice survives a reload', async ({ page }) => {
    const editor = new Editor(page)
    await editor.open({ newTableId: 'app-default' })
    await editor.chooseNewTableId('uuid')
    await page.reload()

    await expect(editor.newTableIdSelect()).toHaveValue('uuid')
    await newTable(page)
    await expect(editor.node('table_1')).toContainText('uuid')
  })

  test('the choice survives starting a new project', async ({ page }) => {
    await page.addInitScript(() => {
      if (!localStorage.getItem('e2e:seeded')) {
        localStorage.setItem('e2e:seeded', '1')
        localStorage.setItem('forge:project', '{"hello":"world"}')
      }
    })
    const editor = new Editor(page)
    await editor.open({ newTableId: 'app-default' })
    await editor.chooseNewTableId('uuid')
    await page.getByRole('button', { name: 'Start a new project' }).click()

    await expect(editor.newTableIdSelect()).toHaveValue('uuid')
    await newTable(page)
    await expect(editor.node('table_1')).toContainText('uuid')
  })

  test('a broken saved choice falls back to the default', async ({ page }) => {
    await page.addInitScript(() => {
      localStorage.setItem('forge:settings', '{"newTableId":"bigint"}')
    })
    const editor = new Editor(page)
    await editor.open({ newTableId: 'app-default' })
    await expect(editor.newTableIdSelect()).toHaveValue('integer')
  })
})

test.describe('auto-generate on a column', () => {
  test('can be toggled for an integer column and shows in the DDL', async ({
    page,
  }) => {
    const editor = new Editor(page)
    await editor.open()
    await editor.defineTable('t', [
      { name: 'id', type: 'integer', primaryKey: true },
    ])
    const generate = page.getByRole('checkbox', { name: 'Auto-generate' })
    await expect(generate).not.toBeChecked()

    await generate.check()
    await expect(
      editor.node('t').locator('.table-node__badge', { hasText: 'auto' })
    ).toBeVisible()
    expect(await editor.ddl()).toContain(
      '"id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY'
    )
  })

  test('is offered only for the types a database can generate', async ({
    page,
  }) => {
    const editor = new Editor(page)
    await editor.open()
    await editor.defineTable('t', [{ name: 'c', type: 'text' }])
    const generate = page.getByRole('checkbox', { name: 'Auto-generate' })
    await expect(generate).toHaveCount(0)

    for (const type of ['integer', 'bigint', 'uuid'] as const) {
      await editor
        .columnRows()
        .first()
        .getByRole('combobox', { name: 'Column type' })
        .selectOption(type)
      await expect(generate).toHaveCount(1)
    }
    await editor
      .columnRows()
      .first()
      .getByRole('combobox', { name: 'Column type' })
      .selectOption('boolean')
    await expect(generate).toHaveCount(0)
  })

  test('is cleared when the column changes to a type that cannot be generated', async ({
    page,
  }) => {
    const editor = new Editor(page)
    await editor.open()
    await editor.defineTable('t', [
      { name: 'id', type: 'integer', primaryKey: true, generated: true },
    ])
    const type = editor
      .columnRows()
      .first()
      .getByRole('combobox', { name: 'Column type' })

    await type.selectOption('text')
    expect(await editor.ddl()).not.toContain('GENERATED')
    await type.selectOption('integer')
    await expect(
      page.getByRole('checkbox', { name: 'Auto-generate' })
    ).not.toBeChecked()
    expect(await editor.ddl()).not.toContain('GENERATED')
  })

  test('a generated id can be referenced by a foreign key', async ({
    page,
  }) => {
    const editor = new Editor(page)
    await editor.open({ newTableId: 'integer' })
    await newTable(page)
    await page.getByRole('textbox', { name: 'Table name' }).fill('users')
    await newTable(page)
    await page.getByRole('textbox', { name: 'Table name' }).fill('orders')
    await editor.addColumn({ name: 'user_id', type: 'integer' })

    await editor.connect(
      { table: 'orders', column: 'user_id' },
      { table: 'users', column: 'id' }
    )
    await expect(editor.edges()).toHaveCount(1)
    expect(await editor.ddl()).toContain(
      'FOREIGN KEY ("user_id") REFERENCES "users" ("id")'
    )
  })
})
