import type { Page } from '@playwright/test'
import { expect, test } from '@playwright/test'

import { Editor } from '../support/editor.ts'

const SCRIPT = `CREATE TABLE KONTRATA_JOBS (
  ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  TITLE VARCHAR2(255) NOT NULL,
  LATITUDE NUMBER,
  ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  PAYLOAD CLOB CHECK (PAYLOAD IS JSON),
  RAW_XML XMLTYPE,
  CONSTRAINT PK_KONTRATA_JOBS PRIMARY KEY (ID),
  CONSTRAINT CK_JOBS_ACTIVE CHECK (ACTIVE IN (0,1))
);
CREATE TABLE KONTRATA_APPLICATIONS (
  ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  JOB_ID NUMBER NOT NULL,
  CONSTRAINT PK_KONTRATA_APPLICATIONS PRIMARY KEY (ID),
  CONSTRAINT FK_APPLICATIONS_JOB FOREIGN KEY (JOB_ID) REFERENCES KONTRATA_JOBS (ID) ON DELETE CASCADE
);
`

const dialog = (page: Page) => page.getByRole('dialog', { name: 'Import SQL' })

async function start(page: Page) {
  await page.setViewportSize({ width: 1400, height: 900 })
  const editor = new Editor(page)
  await editor.open()
  return editor
}

test.describe('reading Oracle SQL', () => {
  test('Read as starts at the project dialect and an Oracle script imports, with upper-case names', async ({
    page,
  }) => {
    const editor = await start(page)
    await page.getByLabel('Dialect').selectOption('oracle')
    await page.getByRole('button', { name: 'Import SQL' }).click()
    await expect(dialog(page).getByLabel('Read as')).toHaveValue('oracle')
    await dialog(page).getByLabel('SQL', { exact: true }).fill(SCRIPT)
    await expect(
      dialog(page).getByRole('region', { name: 'Import preview' })
    ).toContainText('2 tables')
    await dialog(page)
      .getByRole('button', { name: 'Import', exact: true })
      .click()

    await expect(editor.tables()).toHaveCount(2)
    await expect(editor.node('KONTRATA_JOBS')).toBeVisible()
    await expect(editor.edges()).toHaveCount(1)
    await expect(editor.node('KONTRATA_JOBS')).toContainText('number')
    await expect(editor.node('KONTRATA_JOBS')).toContainText('boolean')
    await expect(editor.node('KONTRATA_JOBS')).toContainText('json')
    await expect(editor.node('KONTRATA_JOBS')).toContainText('XMLTYPE')
  })

  test('the Oracle script written back has the same shape', async ({
    page,
  }) => {
    const editor = await start(page)
    await page.getByLabel('Dialect').selectOption('oracle')
    await page.getByRole('button', { name: 'Import SQL' }).click()
    await dialog(page).getByLabel('SQL', { exact: true }).fill(SCRIPT)
    await dialog(page)
      .getByRole('button', { name: 'Import', exact: true })
      .click()
    const sql = await editor.ddl()
    expect(sql).toContain('CREATE TABLE KONTRATA_JOBS (')
    expect(sql).toContain('ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY')
    expect(sql).toContain('LATITUDE NUMBER,')
    expect(sql).toContain('ACTIVE NUMBER(1) DEFAULT 1 NOT NULL')
    expect(sql).toContain('RAW_XML XMLTYPE')
    expect(sql).toContain('CONSTRAINT PK_KONTRATA_JOBS PRIMARY KEY (ID)')
  })

  test('the same script read as PostgreSQL does not understand the Oracle types, and says so by keeping them native', async ({
    page,
  }) => {
    await start(page)
    await page.getByRole('button', { name: 'Import SQL' }).click()
    await dialog(page).getByLabel('Read as').selectOption('oracle')
    await dialog(page).getByLabel('SQL', { exact: true }).fill(SCRIPT)
    await expect(
      dialog(page).getByRole('region', { name: 'Import preview' })
    ).toContainText('2 tables')
    await dialog(page).getByLabel('Read as').selectOption('postgres')
    await expect(
      dialog(page).getByRole('region', { name: 'Import preview' })
    ).toContainText('table')
  })

  test('number and native types show in the Inspector', async ({ page }) => {
    const editor = await start(page)
    await page.getByLabel('Dialect').selectOption('oracle')
    await page.getByRole('button', { name: 'Import SQL' }).click()
    await dialog(page).getByLabel('SQL', { exact: true }).fill(SCRIPT)
    await dialog(page)
      .getByRole('button', { name: 'Import', exact: true })
      .click()
    await editor.selectTable('KONTRATA_JOBS')
    await expect(page.getByLabel('Native type')).toHaveValue('XMLTYPE')
    await expect(
      page.getByRole('combobox', { name: 'Column type' }).nth(2)
    ).toHaveValue('number')
  })

  test('the recruitment example loads, switches the project to Oracle and shows its tables', async ({
    page,
  }) => {
    const editor = await start(page)
    await page.getByRole('button', { name: 'Load recruitment example' }).click()
    await expect(page.getByLabel('Dialect')).toHaveValue('oracle')
    await expect(editor.node('KONTRATA_JOBS')).toBeVisible()
    expect(await editor.tables().count()).toBeGreaterThan(40)
    await editor.showDdl()
    await expect(
      page.getByText('Fix these problems to generate the DDL')
    ).toHaveCount(0)
    expect(await editor.ddl()).toContain('CREATE TABLE KONTRATA_JOBS (')
  })

  test('loading the recruitment example into a project that has tables asks for a second click, and can be undone', async ({
    page,
  }) => {
    const editor = await start(page)
    await editor.addTable('mine')
    await page.getByRole('button', { name: 'Load recruitment example' }).click()
    await expect(editor.node('mine')).toBeVisible()
    await page
      .getByRole('button', {
        name: 'Replace the project with the recruitment example?',
      })
      .click()
    await expect(editor.node('KONTRATA_JOBS')).toBeVisible()
    await page.getByRole('button', { name: 'Undo', exact: true }).click()
    await expect(editor.node('mine')).toBeVisible()
    await expect(editor.tables()).toHaveCount(1)
  })
})
