import { readFileSync } from 'node:fs'

import type { Page } from '@playwright/test'
import { expect, test } from '@playwright/test'

import { Editor } from '../support/editor.ts'

async function exampleInOracle(page: Page) {
  await page.setViewportSize({ width: 1400, height: 900 })
  const editor = new Editor(page)
  await editor.open()
  await page.getByRole('button', { name: 'Load example' }).click()
  await page.getByLabel('Dialect').selectOption('oracle')
  return editor
}

test.describe('the Oracle dialect', () => {
  test('choosing Oracle writes the script in the shape of the team migrations', async ({
    page,
  }) => {
    const editor = await exampleInOracle(page)
    const sql = await editor.ddl()
    expect(sql).toContain('CREATE TABLE USERS (')
    expect(sql).toContain(
      'ID NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY'
    )
    expect(sql).toContain('CONSTRAINT PK_USERS PRIMARY KEY (ID)')
    expect(sql).toContain(
      'CONSTRAINT FK_ORDERS_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS (ID)'
    )
    expect(sql).toContain(
      'CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL'
    )
    expect(sql).toContain(
      "CONSTRAINT CK_ORDERS_STATUS CHECK (STATUS IN ('pending', 'paid', 'shipped', 'cancelled'))"
    )
    expect(sql).not.toContain('CREATE TYPE')
    expect(sql).not.toContain('"')
  })

  test('the notes list what was adapted, and Oracle can be left again', async ({
    page,
  }) => {
    await page.setViewportSize({ width: 1400, height: 900 })
    const editor = new Editor(page)
    await editor.open()
    await page.getByLabel('Dialect').selectOption('oracle')
    await page.getByRole('button', { name: 'Import SQL' }).click()
    await page
      .getByRole('dialog')
      .getByLabel('Read as')
      .selectOption('postgres')
    await page
      .getByRole('dialog')
      .getByLabel('SQL', { exact: true })
      .fill(
        "CREATE TABLE t (id int PRIMARY KEY, tags text[], created timestamptz DEFAULT lower('x'), ok boolean DEFAULT true);"
      )
    await page
      .getByRole('dialog')
      .getByRole('button', { name: 'Import', exact: true })
      .click()
    await editor.showDdl()

    const notes = page.getByRole('list', { name: 'Compatibility notes' })
    await expect(notes).toContainText('stored as a JSON array')
    await expect(notes).toContainText('copied as written')
    // A boolean default of true is translated, not noted.
    await expect(notes).not.toContainText('true')
    await expect(page.getByText(/Compatibility notes \(2\)/)).toBeVisible()
    expect(await editor.ddl()).toContain('OK NUMBER(1) DEFAULT 1')

    await page.getByLabel('Dialect').selectOption('postgres')
    await expect(
      page.getByRole('list', { name: 'Compatibility notes' })
    ).toHaveCount(0)
    expect(await editor.ddl()).toContain('CREATE TABLE "t" (')
  })

  test('an untouched project is saved without a dialect until one is chosen', async ({
    page,
  }) => {
    const editor = new Editor(page)
    await editor.open()
    await editor.addTable('plain')
    await page.waitForTimeout(900)
    const saved = () =>
      page.evaluate(() => window.localStorage.getItem('forge:project') ?? '')
    expect(await saved()).toContain('"plain"')
    expect(await saved()).not.toContain('"dialect"')

    await page.getByLabel('Dialect').selectOption('oracle')
    await page.waitForTimeout(900)
    expect(await saved()).toContain('"dialect":"oracle"')
  })

  test('the uuid option appears only with Oracle and changes the column', async ({
    page,
  }) => {
    await page.setViewportSize({ width: 1400, height: 900 })
    const editor = new Editor(page)
    await editor.open({ newTableId: 'uuid' })
    await expect(page.getByLabel('Oracle uuid')).toHaveCount(0)
    await page.getByRole('button', { name: 'New table' }).click()
    await page.getByLabel('Dialect').selectOption('oracle')
    expect(await editor.ddl()).toContain('ID RAW(16) DEFAULT SYS_GUID()')
    await page.getByLabel('Oracle uuid').selectOption('varchar36')
    expect(await editor.ddl()).toContain(
      'ID VARCHAR2(36) DEFAULT LOWER(REGEXP_REPLACE('
    )
  })

  test('something Oracle refuses is a problem of the schema, not a script', async ({
    page,
  }) => {
    const editor = new Editor(page)
    await editor.open()
    await editor.defineTable('notes', [
      { name: 'body', type: 'text', primaryKey: true },
    ])
    await page.getByLabel('Dialect').selectOption('oracle')
    await editor.showDdl()
    await expect(
      page.getByText('Fix these problems to generate the DDL')
    ).toBeVisible()
    await expect(page.getByText(/cannot be a key in Oracle/)).toBeVisible()
    await page.getByLabel('Dialect').selectOption('postgres')
    await expect(
      page.getByText('Fix these problems to generate the DDL')
    ).toHaveCount(0)
  })

  test('the choice is saved with the project: a reload is still Oracle', async ({
    page,
  }) => {
    const editor = await exampleInOracle(page)
    await page.getByLabel('Oracle uuid').selectOption('varchar36')
    await page.waitForTimeout(800)
    await page.reload()
    await expect(page.getByLabel('Dialect')).toHaveValue('oracle')
    await expect(page.getByLabel('Oracle uuid')).toHaveValue('varchar36')
    expect(await editor.ddl()).toContain('CREATE TABLE USERS (')
  })

  test('changing the dialect is not an undo step', async ({ page }) => {
    const editor = new Editor(page)
    await editor.open()
    await editor.addTable('kept')
    await page.getByLabel('Dialect').selectOption('oracle')
    await page.getByRole('button', { name: 'Undo', exact: true }).click()
    await page.getByRole('button', { name: 'Undo', exact: true }).click()
    await expect(editor.tables()).toHaveCount(0)
    await expect(page.getByLabel('Dialect')).toHaveValue('oracle')
  })

  test('the import dialog reads scripts as the project dialect', async ({
    page,
  }) => {
    await exampleInOracle(page)
    await page.getByRole('button', { name: 'Import SQL' }).click()
    await expect(page.getByRole('dialog')).toContainText(
      'Scripts are read as Oracle.'
    )
    await page.keyboard.press('Escape')
    await page.getByLabel('Dialect').selectOption('postgres')
    await page.getByRole('button', { name: 'Import SQL' }).click()
    await expect(page.getByRole('dialog')).toContainText(
      'Scripts are read as PostgreSQL.'
    )
  })

  test('the downloaded file is the Oracle script', async ({ page }) => {
    const editor = await exampleInOracle(page)
    const shown = await editor.ddl()
    const downloading = page.waitForEvent('download')
    await page.getByRole('button', { name: 'Download .sql' }).click()
    const download = await downloading
    expect(readFileSync(await download.path(), 'utf8')).toBe(shown)
    expect(shown).toContain('CREATE TABLE USERS (')
  })
})
