import assert from 'node:assert/strict'
import { describe, it } from 'node:test'

import { importSql } from '../../../../sql/parse/import-sql.ts'

function run(sql: string) {
  let counter = 0
  return importSql(sql, () => `id-${++counter}`)
}
const messages = (list: { message: string }[]) =>
  list.map((item) => item.message)
const tableNamed = (sql: string, name: string) => {
  const found = run(sql).schema.tables.find((table) => table.name === name)
  assert.ok(found, `no table ${name}`)
  return found
}

describe('importSql: nothing to import', () => {
  it('gives an empty schema and no messages for empty input and for only comments', () => {
    for (const sql of ['', '   \n', '-- just a comment\n/* and another */']) {
      const result = run(sql)
      assert.deepEqual(result.schema, {
        version: 1,
        tables: [],
        relationships: [],
      })
      assert.deepEqual(result.warnings, [])
      assert.deepEqual(result.errors, [])
    }
  })
})

describe('importSql: tables and columns', () => {
  const sql = `CREATE TABLE public.Users (
    id integer NOT NULL,
    "Name" varchar(120) NOT NULL,
    bio text,
    PRIMARY KEY (id)
  );`

  it('creates the table, its columns in order, and the primary key', () => {
    const table = tableNamed(sql, 'users')
    assert.deepEqual(
      table.columns.map((c) => c.name),
      ['id', 'Name', 'bio']
    )
    assert.deepEqual(table.primaryKey, [table.columns[0]?.id])
    assert.deepEqual(
      table.columns.map((c) => c.nullable),
      [false, false, true]
    )
    assert.deepEqual(table.columns[1]?.type, { kind: 'varchar', length: 120 })
  })

  it('takes the primary key from a column, a table constraint or an ALTER', () => {
    const inline = tableNamed('CREATE TABLE t (a int PRIMARY KEY, b int)', 't')
    assert.deepEqual(inline.primaryKey, [inline.columns[0]?.id])
    const composite = tableNamed(
      'CREATE TABLE t (a int, b int, PRIMARY KEY (a, b))',
      't'
    )
    assert.equal(composite.primaryKey.length, 2)
    const altered = tableNamed(
      'CREATE TABLE t (a int, b int); ALTER TABLE ONLY public.t ADD CONSTRAINT t_pkey PRIMARY KEY (b);',
      't'
    )
    assert.deepEqual(altered.primaryKey, [altered.columns[1]?.id])
  })

  it('warns about a primary key column that does not exist', () => {
    const result = run('CREATE TABLE t (a int, PRIMARY KEY (zz))')
    assert.equal(result.warnings.length, 1)
  })

  it('keeps the first of two tables with the same name, and of two columns', () => {
    const tables = run('CREATE TABLE t (a int); CREATE TABLE t (b int);')
    assert.equal(tables.schema.tables.length, 1)
    assert.equal(tables.schema.tables[0]?.columns[0]?.name, 'a')
    assert.equal(tables.warnings.length, 1)
    const columns = run('CREATE TABLE t (a int, a text)')
    assert.equal(columns.schema.tables[0]?.columns.length, 1)
    assert.equal(columns.warnings.length, 1)
  })

  it('treats Users and "Users" as different tables', () => {
    assert.equal(
      run('CREATE TABLE Users (a int); CREATE TABLE "Users" (a int);').schema
        .tables.length,
      2
    )
  })
})

describe('importSql: generated columns and defaults', () => {
  const column = (sql: string, name: string) => {
    const found = tableNamed(sql, 't').columns.find((c) => c.name === name)
    assert.ok(found)
    return found
  }

  it('turns identity, serial, now() and a uuid function into generated columns', () => {
    const sql = `CREATE TABLE t (
      a integer GENERATED BY DEFAULT AS IDENTITY,
      b bigserial,
      c timestamptz DEFAULT now() NOT NULL,
      d timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
      e uuid DEFAULT gen_random_uuid(),
      f uuid DEFAULT public.uuid_generate_v4(),
      g integer DEFAULT nextval('t_g_seq'::regclass)
    )`
    for (const name of ['a', 'b', 'c', 'd', 'e', 'f', 'g']) {
      assert.equal(column(sql, name).generated, true, name)
      assert.equal(column(sql, name).default, undefined, name)
    }
    assert.equal(column(sql, 'a').nullable, false)
    assert.equal(column(sql, 'b').nullable, false)
    assert.equal(column(sql, 'e').nullable, true)
    assert.equal(run(sql).warnings.length, 0)
  })

  it('keeps any other default raw, and a now() default on a timestamp without time zone', () => {
    const sql = `CREATE TABLE t (
      a integer DEFAULT 0,
      b text DEFAULT 'x',
      c timestamp DEFAULT now(),
      d integer GENERATED ALWAYS AS IDENTITY
    )`
    assert.equal(column(sql, 'a').default, '0')
    assert.equal(column(sql, 'b').default, "'x'")
    assert.equal(column(sql, 'c').default, 'now()')
    assert.equal(column(sql, 'c').generated, undefined)
  })

  it('keeps a now() default with a cast to anything but a timestamp as a raw default', () => {
    const sql = `CREATE TABLE t (a timestamptz DEFAULT now()::date, b timestamptz DEFAULT now()::timestamp with time zone)`
    assert.equal(column(sql, 'a').generated, undefined)
    assert.equal(column(sql, 'a').default, 'now()::date')
    assert.equal(column(sql, 'b').generated, true)
  })

  it('imports a smallint serial as a plain smallint NOT NULL, with a warning', () => {
    const result = run('CREATE TABLE t (a smallserial)')
    const found = result.schema.tables[0]?.columns[0]
    assert.deepEqual(found?.type, { kind: 'smallint' })
    assert.equal(found?.generated, undefined)
    assert.equal(found?.nullable, false)
    assert.equal(result.warnings.length, 1)
  })
})

describe('importSql: types', () => {
  const sql = `
    CREATE TABLE orders (id int, status public.order_status NOT NULL DEFAULT 'pending', tags order_status[], mood sad_mood);
    CREATE TYPE order_status AS ENUM ('pending', 'paid');
    CREATE DOMAIN email AS text NOT NULL;
    CREATE TABLE people (address email);`

  it('resolves a type defined after the table that uses it, and arrays of it', () => {
    const result = run(sql)
    const typeId = result.schema.types?.find(
      (t) => t.name === 'order_status'
    )?.id
    assert.ok(typeId)
    const orders = result.schema.tables[0]
    assert.deepEqual(orders?.columns[1]?.type, { kind: 'user', typeId })
    assert.equal(orders?.columns[1]?.default, "'pending'")
    assert.deepEqual(orders?.columns[2]?.type, {
      kind: 'array',
      of: { kind: 'user', typeId },
    })
  })

  it('creates enums and domains, and resolves a domain used as a column type', () => {
    const result = run(sql)
    assert.deepEqual(
      result.schema.types?.map((t) => [t.kind, t.name]),
      [
        ['enum', 'order_status'],
        ['domain', 'email'],
      ]
    )
    const domainId = result.schema.types?.[1]?.id
    assert.deepEqual(result.schema.tables[1]?.columns[0]?.type, {
      kind: 'user',
      typeId: domainId,
    })
  })

  it('keeps an unknown type as a native type, with no warning', () => {
    const result = run(sql)
    assert.deepEqual(result.schema.tables[0]?.columns[3]?.type, {
      kind: 'native',
      dialect: 'postgres',
      text: 'sad_mood',
    })
    assert.ok(!messages(result.warnings).some((m) => m.includes('sad_mood')))
  })

  it('keeps the first of two types with the same name', () => {
    const result = run(
      "CREATE TYPE e AS ENUM ('a'); CREATE TYPE e AS ENUM ('b');"
    )
    assert.equal(result.schema.types?.length, 1)
    assert.equal(result.warnings.length, 1)
  })
})

describe('importSql: foreign keys', () => {
  const parent = 'CREATE TABLE users (id int PRIMARY KEY, code text UNIQUE);'
  const relationships = (sql: string) => run(sql).schema.relationships

  it('reads inline, table-level and ALTER foreign keys, to a table defined later too', () => {
    const sql = `
      CREATE TABLE a (id int PRIMARY KEY, user_id int REFERENCES users (id));
      CREATE TABLE b (id int PRIMARY KEY, user_id int, FOREIGN KEY (user_id) REFERENCES users (id));
      CREATE TABLE c (id int PRIMARY KEY, user_id int);
      ALTER TABLE ONLY c ADD CONSTRAINT fk FOREIGN KEY (user_id) REFERENCES public.users (id);
      ${parent}`
    const result = run(sql)
    assert.equal(result.schema.relationships.length, 3)
    assert.deepEqual(result.warnings, [])
    const [first] = result.schema.relationships
    const users = result.schema.tables.find((t) => t.name === 'users')
    assert.equal(first?.to.tableId, users?.id)
    assert.equal(first?.to.columnId, users?.columns[0]?.id)
  })

  it('uses the sole primary key when the column is not written', () => {
    assert.equal(
      relationships(
        `${parent} CREATE TABLE a (id int, user_id int REFERENCES users);`
      ).length,
      1
    )
  })

  it('drops, with a warning, a key to an unknown table or column, a composite key, and a non-primary-key target', () => {
    const cases: [string, string][] = [
      [`${parent} CREATE TABLE a (user_id int REFERENCES nope (id))`, 'nope'],
      [`${parent} CREATE TABLE a (user_id int REFERENCES users (zz))`, 'zz'],
      [
        `${parent} CREATE TABLE a (x int, y int, FOREIGN KEY (x, y) REFERENCES users (id, code))`,
        'composite',
      ],
      [
        `${parent} CREATE TABLE a (user_id text REFERENCES users (code))`,
        'primary key',
      ],
      [
        `${parent} CREATE TABLE a (user_id text REFERENCES users (id))`,
        'types differ',
      ],
      [
        `${parent} ALTER TABLE ghost ADD FOREIGN KEY (x) REFERENCES users (id)`,
        'ghost',
      ],
    ]
    for (const [sql, fragment] of cases) {
      const result = run(sql)
      assert.equal(result.schema.relationships.length, 0, sql)
      assert.ok(
        messages(result.warnings).some((m) =>
          m.toLowerCase().includes(fragment)
        ),
        `${sql} → ${JSON.stringify(messages(result.warnings))}`
      )
      assert.deepEqual(result.errors, [], sql)
    }
  })

  it('keeps the key and warns that ON DELETE / ON UPDATE actions are ignored', () => {
    const result = run(
      `${parent} CREATE TABLE a (user_id int REFERENCES users (id) ON DELETE CASCADE)`
    )
    assert.equal(result.schema.relationships.length, 1)
    assert.equal(result.warnings.length, 1)
  })

  it('keeps only one key from a column that references twice', () => {
    const sql = `${parent} CREATE TABLE a (user_id int REFERENCES users (id)); ALTER TABLE a ADD FOREIGN KEY (user_id) REFERENCES users (id);`
    assert.equal(run(sql).schema.relationships.length, 1)
  })
})

describe('importSql: indexes', () => {
  const indexes = (sql: string) => run(sql).schema.tables[0]?.indexes ?? []

  it('turns UNIQUE into unique indexes named after the constraint, or uq_<table>_<columns>', () => {
    const list = indexes(
      `CREATE TABLE t (a int UNIQUE, b int, c int, UNIQUE (b, c), CONSTRAINT t_c_key UNIQUE (c))`
    )
    assert.deepEqual(
      list.map((i) => [i.name, i.unique, i.columns.length]),
      [
        ['uq_t_a', true, 1],
        ['uq_t_b_c', true, 2],
        ['t_c_key', true, 1],
      ]
    )
  })

  it('reads CREATE INDEX, naming an unnamed one idx_<table>_<columns>', () => {
    const list = indexes(
      'CREATE TABLE t (a int, b int); CREATE INDEX ON t USING gin (a, b); CREATE INDEX i ON t (b);'
    )
    assert.deepEqual(
      list.map((i) => [i.name, i.method]),
      [
        ['idx_t_a_b', 'gin'],
        ['i', 'btree'],
      ]
    )
  })

  it('renames a name that is already taken, and skips a repeated unique index', () => {
    const renamed = run(
      'CREATE TABLE t (a int, b int); CREATE INDEX i ON t (a); CREATE INDEX i ON t (b);'
    )
    assert.deepEqual(
      renamed.schema.tables[0]?.indexes?.map((i) => i.name),
      ['i', 'i_2']
    )
    assert.equal(renamed.warnings.length, 1)
    assert.equal(
      indexes('CREATE TABLE t (a int UNIQUE); CREATE UNIQUE INDEX u ON t (a);')
        .length,
      1
    )
  })

  it('warns about an index on an unknown table or column', () => {
    const result = run(
      'CREATE TABLE t (a int); CREATE INDEX i ON nope (a); CREATE INDEX j ON t (zz);'
    )
    assert.equal(result.warnings.length, 2)
    assert.equal(result.schema.tables[0]?.indexes, undefined)
  })
})

describe('importSql: comments and sequences', () => {
  it('applies table and column comments, and warns about unknown targets', () => {
    const result = run(`CREATE TABLE t (a int);
      COMMENT ON TABLE t IS 'People';
      COMMENT ON COLUMN public.t.a IS 'The key';
      COMMENT ON TABLE ghost IS 'x';
      COMMENT ON COLUMN t.zz IS 'x';`)
    assert.equal(result.schema.tables[0]?.comment, 'People')
    assert.equal(result.schema.tables[0]?.columns[0]?.comment, 'The key')
    assert.equal(result.warnings.length, 2)
  })

  it('reads a default set by ALTER COLUMN, and an identity added by ALTER COLUMN, as pg_dump writes them', () => {
    const result =
      run(`CREATE TABLE t (id integer NOT NULL, n integer, c integer);
      ALTER TABLE ONLY public.t ALTER COLUMN id SET DEFAULT nextval('public.t_id_seq'::regclass);
      ALTER TABLE ONLY public.t ALTER COLUMN n SET DEFAULT 5;
      ALTER TABLE public.t ALTER COLUMN c ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.t_c_seq START WITH 1);`)
    const [id, n, c] = result.schema.tables[0]?.columns ?? []
    assert.equal(id?.generated, true)
    assert.equal(n?.default, '5')
    assert.equal(c?.generated, true)
  })
})

describe('importSql: a smallint identity', () => {
  it('is imported as a plain smallint that is NOT NULL', () => {
    const column = run(
      'CREATE TABLE t (a smallint GENERATED ALWAYS AS IDENTITY)'
    ).schema.tables[0]?.columns[0]
    assert.equal(column?.nullable, false)
    assert.equal(column?.generated, undefined)
  })
})

describe('importSql: ALTER TABLE on what does not exist', () => {
  it('warns about a primary key, a default and an identity on an unknown table or column', () => {
    const cases: [string, string][] = [
      ['ALTER TABLE ghost ADD PRIMARY KEY (id)', 'ghost'],
      [
        'CREATE TABLE t (a int); ALTER TABLE t ALTER COLUMN zz SET DEFAULT 1',
        'zz',
      ],
      [
        'CREATE TABLE t (a int); ALTER TABLE t ALTER COLUMN zz ADD GENERATED ALWAYS AS IDENTITY',
        'zz',
      ],
      ['ALTER TABLE ghost ALTER COLUMN a SET DEFAULT 1', 'ghost'],
    ]
    for (const [sql, fragment] of cases) {
      const result = run(sql)
      assert.ok(
        messages(result.warnings).some((m) => m.includes(fragment)),
        `${sql} → ${JSON.stringify(messages(result.warnings))}`
      )
      assert.deepEqual(result.errors, [], sql)
    }
  })
})

describe('importSql: an index that repeats a column', () => {
  it('keeps the column once and warns, instead of failing the whole import', () => {
    const result = run(
      'CREATE TABLE t (a int, b int); CREATE INDEX i ON t (a, b, a);'
    )
    assert.deepEqual(result.errors, [])
    assert.equal(result.schema.tables[0]?.indexes?.[0]?.columns.length, 2)
    assert.equal(result.warnings.length, 1)
  })
})

describe('importSql: the same error twice', () => {
  it('is reported once, like the same warning', () => {
    const result = run('CREATE TABLE b (y); CREATE TABLE b (y);')
    assert.equal(result.errors.length, 1)
  })
})

describe('importSql: a script that is cut short', () => {
  it('keeps a last statement that is complete, and says only that the script is cut', () => {
    const result = run('CREATE TABLE a (x int)\n/* oops')
    assert.deepEqual(
      result.schema.tables.map((t) => t.name),
      ['a']
    )
    assert.equal(result.errors.length, 1)
    assert.deepEqual(result.warnings, [])
  })

  it('does not report a stump as an ignored statement', () => {
    const result = run("CREATE TABLE a (x int);\nSELECT ';' 'oops")
    assert.equal(result.errors.length, 1)
    assert.deepEqual(result.warnings, [])
  })

  it('drops a last statement that is cut in the middle', () => {
    const result = run(
      "CREATE TABLE a (x int);\nCREATE TABLE b (y text DEFAULT 'oops"
    )
    assert.deepEqual(
      result.schema.tables.map((t) => t.name),
      ['a']
    )
    assert.equal(result.errors.length, 1)
  })
})

describe('importSql: messages', () => {
  it('reports a warning with its line and the statement', () => {
    const result = run('CREATE TABLE t (a int);\n\nINSERT INTO t VALUES (1);')
    assert.deepEqual(result.warnings, [
      {
        line: 3,
        statement: 'INSERT INTO t VALUES (1)',
        message: 'INSERT INTO statements are not modelled and were ignored.',
      },
    ])
  })

  it('reports a syntax error with its line, and still imports the other statements', () => {
    const result = run(
      'CREATE TABLE a (x int);\nCREATE TABLE b (y);\nCREATE TABLE c (z int);'
    )
    assert.equal(result.errors.length, 1)
    assert.equal(result.errors[0]?.line, 2)
    assert.deepEqual(
      result.schema.tables.map((t) => t.name),
      ['a', 'c']
    )
  })

  it('reports a truncated script as an error and keeps what came before', () => {
    const result = run(
      "CREATE TABLE a (x int);\nCREATE TABLE b (y text DEFAULT 'oops"
    )
    assert.equal(result.errors.length, 1)
    assert.equal(result.errors[0]?.line, 2)
    assert.deepEqual(
      result.schema.tables.map((t) => t.name),
      ['a']
    )
  })

  it('turns the issues of the schema into errors', () => {
    const result = run('CREATE TYPE e AS ENUM ();')
    assert.equal(result.errors.length, 1)
    assert.equal(result.errors[0]?.line, 0)
  })

  it('does not repeat the same warning for the same statement text on the same line', () => {
    assert.equal(
      run('CREATE TABLE t (a int); SET x = 1; SET x = 1;').warnings.length,
      1
    )
    assert.equal(run('SET x = 1;\nSET x = 1;').warnings.length, 2)
  })
})
