import assert from 'node:assert/strict'
import { describe, it } from 'node:test'

import { Cursor, ParseFailure } from '../../../../sql/parse/cursor.ts'
import { parseColumnType } from '../../../../sql/parse/parse-type.ts'
import { tokenize } from '../../../../sql/parse/tokenize.ts'

function typeOf(sql: string) {
  const warnings: string[] = []
  const cursor = new Cursor(
    tokenize(sql, 'oracle').tokens,
    sql,
    (_l, m) => warnings.push(m),
    'oracle'
  )
  const parsed = parseColumnType(cursor)
  return { ...parsed, warnings, rest: cursor.done ? '' : cursor.peek()?.text }
}

describe('Cursor in Oracle: names', () => {
  it('folds a plain word to upper case and keeps a quoted name', () => {
    const sql = 'kontrata_jobs "Mixed" plain'
    const cursor = new Cursor(
      tokenize(sql, 'oracle').tokens,
      sql,
      () => {},
      'oracle'
    )
    assert.deepEqual(
      [cursor.identifier('a'), cursor.identifier('a'), cursor.identifier('a')],
      ['KONTRATA_JOBS', 'Mixed', 'PLAIN']
    )
    const pg = new Cursor(tokenize(sql).tokens, sql, () => {})
    assert.equal(pg.identifier('a'), 'kontrata_jobs')
  })
})

describe('parseOracleType', () => {
  const cases: [string, object][] = [
    ['VARCHAR2(255)', { kind: 'varchar', length: 255 }],
    ['VARCHAR2(100 CHAR)', { kind: 'varchar', length: 100 }],
    ['VARCHAR2(100 BYTE)', { kind: 'varchar', length: 100 }],
    ['CHAR(2)', { kind: 'char', length: 2 }],
    ['CLOB', { kind: 'text' }],
    ['BLOB', { kind: 'bytea' }],
    ['RAW(16)', { kind: 'uuid' }],
    ['RAW(8)', { kind: 'bytea' }],
    ['NUMBER', { kind: 'number' }],
    ['NUMBER(*,2)', { kind: 'number' }],
    ['NUMBER(1)', { kind: 'smallint' }],
    ['NUMBER(4)', { kind: 'smallint' }],
    ['NUMBER(5)', { kind: 'integer' }],
    ['NUMBER(9,0)', { kind: 'integer' }],
    ['NUMBER(10)', { kind: 'bigint' }],
    ['NUMBER(18)', { kind: 'bigint' }],
    ['NUMBER(19)', { kind: 'bigint' }],
    ['NUMBER(20)', { kind: 'numeric', precision: 20, scale: 0 }],
    ['NUMBER(12,2)', { kind: 'numeric', precision: 12, scale: 2 }],
    ['INTEGER', { kind: 'integer' }],
    ['FLOAT', { kind: 'double' }],
    ['FLOAT(10)', { kind: 'real' }],
    ['BINARY_FLOAT', { kind: 'real' }],
    ['BINARY_DOUBLE', { kind: 'double' }],
    ['DATE', { kind: 'date' }],
    ['TIMESTAMP', { kind: 'timestamp_no_tz' }],
    ['TIMESTAMP(6)', { kind: 'timestamp_no_tz' }],
    ['TIMESTAMP WITH TIME ZONE', { kind: 'timestamp' }],
    ['TIMESTAMP(3) WITH TIME ZONE', { kind: 'timestamp' }],
    ['INTERVAL DAY TO SECOND', { kind: 'interval' }],
    ['INTERVAL DAY(0) TO SECOND(0)', { kind: 'interval' }],
    [
      'NVARCHAR2(100)',
      { kind: 'native', dialect: 'oracle', text: 'NVARCHAR2(100)' },
    ],
    ['NCLOB', { kind: 'native', dialect: 'oracle', text: 'NCLOB' }],
    ['ROWID', { kind: 'native', dialect: 'oracle', text: 'ROWID' }],
    ['XMLTYPE', { kind: 'native', dialect: 'oracle', text: 'XMLTYPE' }],
    ['SYS.XMLTYPE', { kind: 'native', dialect: 'oracle', text: 'SYS.XMLTYPE' }],
    [
      'INTERVAL YEAR TO MONTH',
      { kind: 'native', dialect: 'oracle', text: 'INTERVAL YEAR TO MONTH' },
    ],
    [
      'TIMESTAMP WITH LOCAL TIME ZONE',
      {
        kind: 'native',
        dialect: 'oracle',
        text: 'TIMESTAMP WITH LOCAL TIME ZONE',
      },
    ],
  ]
  for (const [sql, expected] of cases) {
    it(`reads ${sql}`, () => assert.deepEqual(typeOf(sql).type, expected))
  }

  it('stops after the type, leaving the rest', () => {
    assert.equal(typeOf('NUMBER GENERATED BY DEFAULT').rest, 'GENERATED')
    assert.equal(typeOf('VARCHAR2(20) NOT NULL').rest, 'NOT')
  })

  it('never reads a serial, and fails when there is no type or VARCHAR2 has no length', () => {
    assert.equal(typeOf('NUMBER').serial, false)
    assert.throws(() => typeOf(''), ParseFailure)
    assert.throws(() => typeOf('VARCHAR2'), ParseFailure)
  })
})
