import assert from 'node:assert/strict'
import { describe, it } from 'node:test'

import { parseScript } from '../../../helpers/parse-script.ts'

const tableOf = (sql: string) => {
  const result = parseScript(sql, 'oracle')
  assert.deepEqual(result.failures, [])
  const table = result.raw.tables[0]
  assert.ok(table)
  return { table, warnings: result.warnings }
}

describe('Oracle CREATE TABLE', () => {
  it('reads the identity, the primary key and unique as they are written in the migrations', () => {
    const { table, warnings } = tableOf(`CREATE TABLE KONTRATA_CANDIDATES (
      ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
      EMAIL VARCHAR2(255) NOT NULL,
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT PK_KONTRATA_CANDIDATES PRIMARY KEY (ID),
      CONSTRAINT UQ_KONTRATA_CANDIDATES_EMAIL UNIQUE (EMAIL)
    );`)
    assert.equal(table.name, 'KONTRATA_CANDIDATES')
    assert.deepEqual(
      table.columns.map((c) => [c.name, c.generated, c.notNull]),
      [
        ['ID', true, true],
        ['EMAIL', false, true],
        ['CREATED_AT', false, true],
      ]
    )
    assert.equal(table.columns[2]?.default, 'SYSTIMESTAMP')
    assert.deepEqual(table.primaryKey, ['ID'])
    assert.deepEqual(table.uniques, [
      { name: 'UQ_KONTRATA_CANDIDATES_EMAIL', columns: ['EMAIL'] },
    ])
    assert.deepEqual(warnings, [])
  })

  it('reads foreign keys with ON DELETE CASCADE, and warns about the action', () => {
    const { table, warnings } = tableOf(`CREATE TABLE A (
      ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
      JOB_ID NUMBER NOT NULL,
      CONSTRAINT FK_A_JOB FOREIGN KEY (JOB_ID)
        REFERENCES KONTRATA_JOBS (ID) ON DELETE CASCADE
    );`)
    assert.deepEqual(table.foreignKeys, [
      {
        columns: ['JOB_ID'],
        reference: { table: 'KONTRATA_JOBS', columns: ['ID'], actions: true },
      },
    ])
    assert.deepEqual(warnings, [])
  })

  it('hints boolean for IN (0,1) and json for IS JSON, at column level and table level', () => {
    const { table, warnings } = tableOf(`CREATE TABLE T (
      A NUMBER(1) DEFAULT 0 NOT NULL CHECK (A IN (0,1)),
      B CLOB NOT NULL CHECK (B IS JSON),
      C NUMBER(1),
      D CLOB,
      E NUMBER(1),
      CONSTRAINT CK_T_C CHECK (C IN (0,1)),
      CONSTRAINT CK_T_D CHECK (D IS JSON STRICT),
      CONSTRAINT CK_T_E CHECK (E IN ('X','Y'))
    );`)
    assert.equal(table.columns[0]?.hint, 'boolean')
    assert.equal(table.columns[1]?.hint, 'json')
    assert.deepEqual(table.hints, [
      { column: 'C', hint: 'boolean' },
      { column: 'D', hint: 'json' },
    ])
    assert.equal(warnings.length, 1)
    assert.ok(warnings[0]?.includes('CHECK'))
  })

  it('skips ENABLE, VALIDATE and USING INDEX after a constraint', () => {
    const { table, warnings } = tableOf(`CREATE TABLE T (
      ID NUMBER,
      CONSTRAINT PK_T PRIMARY KEY (ID) USING INDEX ENABLE,
      X NUMBER CONSTRAINT NN NOT NULL ENABLE VALIDATE
    );`)
    assert.deepEqual(table.primaryKey, ['ID'])
    assert.equal(table.columns[1]?.notNull, true)
    assert.deepEqual(warnings, [])
  })

  it('warns once about the physical clauses after the closing parenthesis, and keeps the table', () => {
    const { table, warnings } = tableOf(
      'CREATE TABLE T (ID NUMBER) TABLESPACE USERS PCTFREE 10;'
    )
    assert.equal(table.columns.length, 1)
    assert.equal(warnings.length, 1)
  })

  it('reads DEFAULT ON NULL', () => {
    const { table } = tableOf(
      'CREATE TABLE T (X NUMBER DEFAULT ON NULL 5 NOT NULL);'
    )
    assert.equal(table.columns[0]?.default, '5')
  })
})
