import assert from 'node:assert/strict'
import { describe, it } from 'node:test'

import { parseScript } from '../../../helpers/parse-script.ts'

describe('ALTER TABLE', () => {
  it('reads ADD CONSTRAINT for a primary key, a unique and a foreign key', () => {
    const sql = `
      ALTER TABLE ONLY public.orders ADD CONSTRAINT orders_pkey PRIMARY KEY (id);
      ALTER TABLE public.orders ADD UNIQUE (code);
      ALTER TABLE ONLY orders
        ADD CONSTRAINT fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;`
    const { raw, failures, warnings } = parseScript(sql)
    assert.deepEqual(failures, [])
    assert.deepEqual(warnings, [])
    assert.deepEqual(
      raw.alters.map(({ origin: _origin, ...rest }) => rest),
      [
        { table: 'orders', primaryKey: ['id'] },
        { table: 'orders', unique: { columns: ['code'] } },
        {
          table: 'orders',
          foreignKey: {
            columns: ['user_id'],
            reference: { table: 'users', columns: ['id'], actions: true },
          },
        },
      ]
    )
  })

  it('reads several actions in one statement and warns about the ones it does not model', () => {
    const { raw, warnings } = parseScript(
      'ALTER TABLE t ADD PRIMARY KEY (a), OWNER TO me, ADD CHECK (a > 0), ENABLE ROW LEVEL SECURITY'
    )
    assert.equal(raw.alters.length, 1)
    assert.equal(warnings.length, 3)
  })

  it('reads ALTER COLUMN SET DEFAULT and ADD GENERATED, as pg_dump writes a serial', () => {
    const { raw, warnings } = parseScript(`
      ALTER TABLE ONLY public.t ALTER COLUMN id SET DEFAULT nextval('public.t_id_seq'::regclass);
      ALTER TABLE public.t ALTER COLUMN n ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.t_n_seq START WITH 1);
      ALTER TABLE t ALTER COLUMN x SET NOT NULL;`)
    assert.deepEqual(
      raw.alters.map(({ origin: _origin, ...rest }) => rest),
      [
        {
          table: 't',
          setDefault: {
            column: 'id',
            expression: "nextval('public.t_id_seq'::regclass)",
          },
        },
        { table: 't', identity: 'n' },
      ]
    )
    assert.equal(warnings.length, 1)
  })

  it('warns about ADD COLUMN, which is not modelled', () => {
    const { raw, warnings } = parseScript('ALTER TABLE t ADD COLUMN x int')
    assert.equal(raw.alters.length, 0)
    assert.equal(warnings.length, 1)
  })

  it('warns about ALTER statements for other objects', () => {
    const { warnings } = parseScript(
      'ALTER SEQUENCE s OWNED BY t.id; ALTER TYPE x OWNER TO me'
    )
    assert.equal(warnings.length, 2)
  })
})

describe('CREATE INDEX', () => {
  const indexOf = (sql: string) => {
    const result = parseScript(sql)
    assert.deepEqual(result.failures, [])
    return { index: result.raw.indexes[0], warnings: result.warnings }
  }

  it('reads a plain, a unique, a named-method and an unnamed index', () => {
    const { index } = indexOf(
      'CREATE INDEX idx_a ON public.t USING btree (a, "B")'
    )
    assert.deepEqual(
      { ...index, origin: undefined },
      {
        origin: undefined,
        name: 'idx_a',
        table: 't',
        columns: ['a', 'B'],
        unique: false,
        method: 'btree',
      }
    )
    assert.equal(
      indexOf('CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS u ON t (a)').index
        ?.unique,
      true
    )
    assert.equal(
      indexOf('CREATE INDEX ON t USING gin (a)').index?.name,
      undefined
    )
    assert.equal(
      indexOf('CREATE INDEX ON t USING gin (a)').index?.method,
      'gin'
    )
    assert.equal(
      indexOf('CREATE INDEX i ON ONLY t (a) WITH (fillfactor = 70)').index
        ?.columns[0],
      'a'
    )
  })

  it('warns and drops an index with an expression, ordering, INCLUDE, WHERE or another method', () => {
    for (const sql of [
      'CREATE INDEX i ON t (lower(a))',
      'CREATE INDEX i ON t (a DESC)',
      'CREATE INDEX i ON t (a NULLS FIRST)',
      'CREATE INDEX i ON t (a text_pattern_ops)',
      'CREATE INDEX i ON t (a) INCLUDE (b)',
      'CREATE INDEX i ON t (a) WHERE a > 0',
      'CREATE INDEX i ON t USING brin (a)',
    ]) {
      const { index, warnings } = indexOf(sql)
      assert.equal(index, undefined, sql)
      assert.equal(warnings.length, 1, sql)
      assert.ok(warnings[0]?.includes('"i"'), sql)
    }
  })
})

describe('CREATE TYPE', () => {
  it('reads an enum with its values, in order', () => {
    const { raw, failures } = parseScript(
      "CREATE TYPE public.mood AS ENUM ('sad', 'it''s ok', 'happy')"
    )
    assert.deepEqual(failures, [])
    assert.equal(raw.types[0]?.kind, 'enum')
    assert.equal(raw.types[0]?.name, 'mood')
    assert.deepEqual(raw.types[0]?.kind === 'enum' && raw.types[0].values, [
      'sad',
      "it's ok",
      'happy',
    ])
  })

  it('reads an enum with no values', () => {
    const { raw } = parseScript('CREATE TYPE e AS ENUM ()')
    assert.deepEqual(raw.types[0]?.kind === 'enum' && raw.types[0].values, [])
  })

  it('warns about composite, range and shell types', () => {
    for (const sql of [
      'CREATE TYPE c AS (a int, b text)',
      'CREATE TYPE r AS RANGE (subtype = int)',
      'CREATE TYPE s',
    ]) {
      const { raw, warnings } = parseScript(sql)
      assert.equal(raw.types.length, 0, sql)
      assert.equal(warnings.length, 1, sql)
    }
  })

  it('fails for an enum value that is not a string', () => {
    assert.equal(parseScript('CREATE TYPE e AS ENUM (1)').failures.length, 1)
  })
})

describe('CREATE DOMAIN', () => {
  it('reads the base type, NOT NULL and a default, and warns about CHECK', () => {
    const { raw, warnings, failures } = parseScript(
      "CREATE DOMAIN public.email AS varchar(255) DEFAULT 'x@y' NOT NULL CONSTRAINT ok CHECK (VALUE LIKE '%@%')"
    )
    assert.deepEqual(failures, [])
    const domain = raw.types[0]
    assert.equal(domain?.kind, 'domain')
    if (domain?.kind === 'domain') {
      assert.equal(domain.name, 'email')
      assert.deepEqual(domain.base, { kind: 'varchar', length: 255 })
      assert.equal(domain.notNull, true)
      assert.equal(domain.default, "'x@y'")
    }
    assert.equal(warnings.length, 1)
  })

  it('accepts a domain without AS and based on another type name', () => {
    const { raw } = parseScript('CREATE DOMAIN d text; CREATE DOMAIN d2 AS d')
    assert.equal(raw.types.length, 2)
    const second = raw.types[1]
    assert.deepEqual(second?.kind === 'domain' && second.base, {
      kind: 'named',
      name: 'd',
    })
  })
})

describe('brackets in a default', () => {
  it('keeps a comma inside brackets in ALTER COLUMN SET DEFAULT and in a domain default', () => {
    const { raw, warnings, failures } = parseScript(`
      ALTER TABLE t ALTER COLUMN a SET DEFAULT ARRAY['x', 'y'];
      CREATE DOMAIN d AS text[] DEFAULT ARRAY['x', 'y'];`)
    assert.deepEqual(failures, [])
    assert.deepEqual(warnings, [])
    const alter = raw.alters[0]
    assert.deepEqual(alter && 'setDefault' in alter && alter.setDefault, {
      column: 'a',
      expression: "ARRAY['x', 'y']",
    })
    const domain = raw.types[0]
    assert.equal(domain?.kind === 'domain' && domain.default, "ARRAY['x', 'y']")
  })
})

describe('COMMENT ON', () => {
  it('reads table and column comments, with or without a schema', () => {
    const { raw, failures, warnings } = parseScript(`
      COMMENT ON TABLE public.users IS 'People';
      COMMENT ON COLUMN public.users.email IS 'it''s the login';
      COMMENT ON COLUMN users.name IS 'Full name';`)
    assert.deepEqual(failures, [])
    assert.deepEqual(warnings, [])
    assert.deepEqual(
      raw.comments.map(({ origin: _origin, ...rest }) => rest),
      [
        { table: 'users', text: 'People' },
        { table: 'users', column: 'email', text: "it's the login" },
        { table: 'users', column: 'name', text: 'Full name' },
      ]
    )
  })

  it('treats IS NULL as nothing, and warns about other objects', () => {
    const { raw, warnings } = parseScript(
      "COMMENT ON TABLE t IS NULL; COMMENT ON FUNCTION f() IS 'x'; COMMENT ON INDEX i IS 'x'"
    )
    assert.equal(raw.comments.length, 0)
    assert.equal(warnings.length, 2)
  })
})

describe('the dispatcher', () => {
  it('reads every kind of statement of a small script', () => {
    const { raw, warnings, failures } = parseScript(`
      CREATE TYPE s AS ENUM ('a');
      CREATE TABLE t (id int);
      CREATE INDEX i ON t (id);
      COMMENT ON TABLE t IS 'x';
      CREATE EXTENSION pgcrypto;
      CREATE VIEW v AS SELECT 1;`)
    assert.deepEqual(failures, [])
    assert.deepEqual(
      [
        raw.types.length,
        raw.tables.length,
        raw.indexes.length,
        raw.comments.length,
      ],
      [1, 1, 1, 1]
    )
    assert.deepEqual(warnings, [
      '6: CREATE EXTENSION statements are not modelled and were ignored.',
      '7: CREATE VIEW statements are not modelled and were ignored.',
    ])
  })
})
