import assert from 'node:assert/strict'
import { describe, it } from 'node:test'

import { parseScript } from '../../../helpers/parse-script.ts'

const tableOf = (sql: string) => {
  const result = parseScript(sql)
  assert.deepEqual(result.failures, [])
  const table = result.raw.tables[0]
  assert.ok(table, 'no table was read')
  return { table, warnings: result.warnings }
}
const column = (sql: string, name: string) => {
  const found = tableOf(sql).table.columns.find((c) => c.name === name)
  assert.ok(found, `no column ${name}`)
  return found
}

describe('CREATE TABLE: the table and its columns', () => {
  it('reads the name (case-folded unless quoted, schema dropped) and the columns in order', () => {
    const { table } = tableOf(
      'CREATE TABLE public.Users (id integer, "Name" text)'
    )
    assert.equal(table.name, 'users')
    assert.deepEqual(
      table.columns.map((c) => c.name),
      ['id', 'Name']
    )
    assert.equal(tableOf('create table "Users" ()').table.name, 'Users')
  })

  it('accepts IF NOT EXISTS, TEMP, UNLOGGED and an empty column list', () => {
    assert.equal(
      tableOf('CREATE UNLOGGED TABLE IF NOT EXISTS t ()').table.columns.length,
      0
    )
    assert.equal(tableOf('CREATE TEMP TABLE t (a int)').table.columns.length, 1)
  })

  it('records where the statement came from', () => {
    const { table } = tableOf('\n\nCREATE   TABLE t (\n a int\n);')
    assert.equal(table.origin.line, 3)
    assert.equal(table.origin.text, 'CREATE TABLE t ( a int )')
  })
})

describe('CREATE TABLE: column constraints', () => {
  it('reads NOT NULL, NULL, PRIMARY KEY and UNIQUE', () => {
    const sql =
      'CREATE TABLE t (a int NOT NULL, b int NULL, c int PRIMARY KEY, d int UNIQUE)'
    assert.equal(column(sql, 'a').notNull, true)
    assert.equal(column(sql, 'b').notNull, false)
    assert.equal(column(sql, 'c').primaryKey, true)
    assert.equal(column(sql, 'd').unique, true)
  })

  it('keeps the source text of a DEFAULT, whatever it contains', () => {
    const sql = `CREATE TABLE t (
      a int DEFAULT 0 NOT NULL,
      b text DEFAULT 'x, y'::text,
      c timestamptz DEFAULT now(),
      d int DEFAULT (1 + 2) * 3,
      e text DEFAULT NULL,
      f int DEFAULT -1 CONSTRAINT nn NOT NULL
    )`
    assert.equal(column(sql, 'a').default, '0')
    assert.equal(column(sql, 'a').notNull, true)
    assert.equal(column(sql, 'b').default, "'x, y'::text")
    assert.equal(column(sql, 'c').default, 'now()')
    assert.equal(column(sql, 'd').default, '(1 + 2) * 3')
    assert.equal(column(sql, 'e').default, 'NULL')
    assert.equal(column(sql, 'f').default, '-1')
    assert.equal(column(sql, 'f').notNull, true)
  })

  it('marks identity columns and serials as generated', () => {
    const sql = `CREATE TABLE t (
      a integer GENERATED ALWAYS AS IDENTITY,
      b bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 10),
      c serial,
      d int
    )`
    assert.equal(column(sql, 'a').generated, true)
    assert.equal(column(sql, 'b').generated, true)
    assert.equal(column(sql, 'c').generated, true)
    assert.equal(column(sql, 'c').notNull, true)
    assert.equal(column(sql, 'd').generated, false)
  })

  it('warns about a generated expression and keeps a plain column', () => {
    const { table, warnings } = tableOf(
      'CREATE TABLE t (a int, b int GENERATED ALWAYS AS (a * 2) STORED)'
    )
    assert.equal(table.columns[1]?.generated, false)
    assert.equal(warnings.length, 1)
  })

  it('reads an inline REFERENCES with and without a column and with actions', () => {
    const sql = `CREATE TABLE t (
      a int REFERENCES users,
      b int REFERENCES public.users (id) ON DELETE CASCADE ON UPDATE NO ACTION,
      c int REFERENCES users (id) NOT NULL,
      d int REFERENCES users (id) MATCH FULL DEFERRABLE INITIALLY DEFERRED
    )`
    assert.deepEqual(column(sql, 'a').reference, {
      table: 'users',
      columns: [],
      actions: false,
    })
    assert.deepEqual(column(sql, 'b').reference, {
      table: 'users',
      columns: ['id'],
      actions: true,
    })
    assert.equal(column(sql, 'c').notNull, true)
    assert.deepEqual(column(sql, 'c').reference, {
      table: 'users',
      columns: ['id'],
      actions: false,
    })
    assert.equal(column(sql, 'd').reference?.actions, false)
  })

  it('warns about CHECK and skips COLLATE and CONSTRAINT names', () => {
    const { table, warnings } = tableOf(
      'CREATE TABLE t (a int CONSTRAINT pos CHECK (a > 0), b text COLLATE "C" NOT NULL)'
    )
    assert.equal(warnings.length, 1)
    assert.equal(table.columns[1]?.notNull, true)
  })
})

describe('CREATE TABLE: brackets in a DEFAULT', () => {
  it('keeps a comma inside brackets as part of the expression', () => {
    const sql = `CREATE TABLE t (
      a text[] DEFAULT ARRAY['a'::text, 'b'::text],
      b int[] DEFAULT ARRAY[NULL]::int[] NOT NULL,
      c int
    )`
    assert.equal(column(sql, 'a').default, "ARRAY['a'::text, 'b'::text]")
    assert.equal(column(sql, 'b').default, 'ARRAY[NULL]::int[]')
    assert.equal(column(sql, 'b').notNull, true)
    assert.equal(tableOf(sql).table.columns.length, 3)
  })
})

describe('CREATE TABLE: table constraints', () => {
  const sql = `CREATE TABLE t (
    a int, b int, c int,
    CONSTRAINT t_pk PRIMARY KEY (a, b),
    UNIQUE (c),
    CONSTRAINT t_c_key UNIQUE (b, c),
    CONSTRAINT t_fk FOREIGN KEY (c) REFERENCES other (id) ON DELETE SET NULL,
    CHECK (a > 0)
  )`

  it('reads PRIMARY KEY, UNIQUE (named or not) and FOREIGN KEY', () => {
    const { table, warnings } = tableOf(sql)
    assert.deepEqual(table.primaryKey, ['a', 'b'])
    assert.deepEqual(table.uniques, [
      { columns: ['c'] },
      { name: 't_c_key', columns: ['b', 'c'] },
    ])
    assert.deepEqual(table.foreignKeys, [
      {
        columns: ['c'],
        reference: { table: 'other', columns: ['id'], actions: true },
      },
    ])
    assert.equal(warnings.length, 1)
  })

  it('warns about EXCLUDE and LIKE, keeping the rest of the table', () => {
    const { table, warnings } = tableOf(
      'CREATE TABLE t (a int, EXCLUDE USING gist (a WITH =), LIKE other)'
    )
    assert.equal(table.columns.length, 1)
    assert.equal(warnings.length, 2)
  })
})

describe('CREATE TABLE: what is not a plain table, and what is wrong', () => {
  it('warns and reads nothing for AS SELECT and PARTITION OF', () => {
    for (const sql of [
      'CREATE TABLE t AS SELECT 1',
      'CREATE TABLE t PARTITION OF p FOR VALUES IN (1)',
    ]) {
      const result = parseScript(sql)
      assert.equal(result.raw.tables.length, 0, sql)
      assert.equal(result.warnings.length, 1, sql)
    }
  })

  it('warns about trailing partitioning or inheritance and keeps the table', () => {
    const result = parseScript('CREATE TABLE t (a int) PARTITION BY RANGE (a)')
    assert.equal(result.raw.tables.length, 1)
    assert.equal(result.warnings.length, 1)
  })

  it('fails with the line for a broken table, and still reads the next statements', () => {
    const result = parseScript(
      'CREATE TABLE a (x int,\n y);\nCREATE TABLE b (z int);'
    )
    assert.equal(result.failures.length, 1)
    assert.equal(result.failures[0]?.line, 2)
    assert.deepEqual(
      result.raw.tables.map((t) => t.name),
      ['b']
    )
  })

  it('fails when the parenthesis is never closed', () => {
    const result = parseScript('CREATE TABLE a (x int')
    assert.equal(result.failures.length, 1)
  })

  it('warns that other statements are not modelled', () => {
    const result = parseScript(
      'INSERT INTO t VALUES (1);\nSET search_path = public;'
    )
    assert.deepEqual(result.warnings, [
      '1: INSERT INTO statements are not modelled and were ignored.',
      '2: SET SEARCH_PATH statements are not modelled and were ignored.',
    ])
  })
})
