import assert from 'node:assert/strict'
import { describe, it } from 'node:test'

import { oracle } from '../../../dialects/oracle.ts'
import { postgres } from '../../../dialects/postgres.ts'
import type { Column, ColumnType, Schema } from '../../../schema/types.ts'
import { generateDdl } from '../../../sql/generate/generate-ddl.ts'

const col = (
  id: string,
  name: string,
  type: ColumnType,
  extra: Partial<Column> = {}
): Column => ({ id, name, type, nullable: true, ...extra })
const schemaOf = (columns: Column[], primaryKey: string[] = []): Schema => ({
  version: 1,
  tables: [{ id: 't', name: 'jobs', columns, primaryKey }],
  relationships: [],
})
const run = (schema: Schema, dialect: typeof postgres) => {
  const result = generateDdl(schema, dialect)
  assert.equal(result.ok, true)
  return result.ok ? result : { sql: '', notes: [], statements: [] }
}

describe('number and native in PostgreSQL', () => {
  const schema = schemaOf(
    [
      col('a', 'id', { kind: 'number' }, { nullable: false, generated: true }),
      col('b', 'latitude', { kind: 'number' }),
      col('c', 'weird', { kind: 'native', dialect: 'postgres', text: 'inet' }),
      col('d', 'rowid', { kind: 'native', dialect: 'oracle', text: 'ROWID' }),
    ],
    ['a']
  )

  it('writes number as numeric, a generated number as bigint with a note, and natives by dialect', () => {
    const { sql, notes } = run(schema, postgres)
    assert.ok(
      sql.includes('"id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY'),
      sql
    )
    assert.ok(sql.includes('"latitude" numeric,'), sql)
    assert.ok(sql.includes('"weird" inet,'), sql)
    assert.ok(sql.includes('"rowid" text'), sql)
    assert.deepEqual(
      notes.map((n) => [n.code, n.columnId]),
      [
        ['identity-as-bigint', 'a'],
        ['native-type', 'd'],
      ]
    )
  })
})

describe('number and native in Oracle', () => {
  const schema = schemaOf(
    [
      col('a', 'id', { kind: 'number' }, { nullable: false, generated: true }),
      col('b', 'latitude', { kind: 'number' }),
      col('c', 'name', {
        kind: 'native',
        dialect: 'oracle',
        text: 'NVARCHAR2(100)',
      }),
      col('d', 'weird', { kind: 'native', dialect: 'postgres', text: 'inet' }),
    ],
    ['a']
  )

  it('writes NUMBER, an identity on it, an Oracle native as it is, and another native as a CLOB with a note', () => {
    const { sql, notes } = run(schema, oracle())
    assert.ok(
      sql.includes('ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,'),
      sql
    )
    assert.ok(sql.includes('LATITUDE NUMBER,'), sql)
    assert.ok(sql.includes('NAME NVARCHAR2(100),'), sql)
    assert.ok(sql.includes('WEIRD CLOB'), sql)
    assert.deepEqual(
      notes.map((n) => [n.code, n.columnId]),
      [['native-type', 'd']]
    )
  })

  it('does not let a native of another database be a key', () => {
    const keyed = schemaOf(
      [col('a', 'k', { kind: 'native', dialect: 'postgres', text: 'inet' })],
      ['a']
    )
    const result = generateDdl(keyed, oracle())
    assert.equal(result.ok, false)
  })
})
