import assert from 'node:assert/strict'
import { describe, it } from 'node:test'

import { oracle } from '../../../dialects/oracle.ts'
import { generateDdl } from '../../../sql/generate/generate-ddl.ts'
import { importSql } from '../../../sql/parse/import-sql.ts'

let counter = 0
const run = (sql: string) => importSql(sql, () => `r-${++counter}`, 'oracle')
const typeOf = (sql: string, table: string, column: string) =>
  run(sql)
    .schema.tables.find((t) => t.name === table)
    ?.columns.find((c) => c.name === column)

describe('Oracle identity on wide NUMBER keeps its identity', () => {
  it('reads NUMBER(19) as bigint, the inverse of the writer', () => {
    const column = typeOf(
      'CREATE TABLE T (ID NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY, CONSTRAINT PK PRIMARY KEY (ID));',
      'T',
      'ID'
    )
    assert.deepEqual(column?.type, { kind: 'bigint' })
    assert.equal(column?.generated, true)
  })

  it('keeps the identity of NUMBER(38,0) as a number', () => {
    const result = run(
      'CREATE TABLE T (ID NUMBER(38,0) GENERATED ALWAYS AS IDENTITY);'
    )
    const column = result.schema.tables[0]?.columns[0]
    assert.deepEqual(column?.type, { kind: 'number' })
    assert.equal(column?.generated, true)
    assert.deepEqual(result.warnings, [])
  })

  it('a bigint identity survives the Oracle round trip', () => {
    const first = run(
      'CREATE TABLE T (ID NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY, CONSTRAINT PK PRIMARY KEY (ID));'
    )
    const ddl = generateDdl(first.schema, oracle())
    assert.equal(ddl.ok, true)
    if (!ddl.ok) return
    const second = run(ddl.sql)
    assert.deepEqual(second.schema.tables[0]?.columns[0]?.type, {
      kind: 'bigint',
    })
    assert.equal(second.schema.tables[0]?.columns[0]?.generated, true)
  })
})

describe('Oracle defaults that are Oracle functions are not noted', () => {
  it('SYSTIMESTAMP on a TIMESTAMP gives no raw-default note', () => {
    const first = run(
      'CREATE TABLE T (C TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL);'
    )
    const ddl = generateDdl(first.schema, oracle())
    assert.equal(ddl.ok, true)
    if (ddl.ok) assert.deepEqual(ddl.notes, [])
  })
})

describe('parentheses inside IS JSON', () => {
  it('do not end the table early', () => {
    const result = run(
      'CREATE TABLE E (I CLOB CHECK (I IS JSON (OBJECT)), J NUMBER(1), K VARCHAR2(10), CONSTRAINT PK PRIMARY KEY (K));'
    )
    const table = result.schema.tables[0]
    assert.deepEqual(
      table?.columns.map((c) => c.name),
      ['I', 'J', 'K']
    )
    assert.deepEqual(table?.columns[0]?.type, { kind: 'json' })
    assert.deepEqual(result.errors, [])
  })
})

describe('ALTER TABLE ADD CONSTRAINT CHECK', () => {
  it('makes a 0/1 column a boolean and an IS JSON column a json', () => {
    const result = run(`
      CREATE TABLE E (FLAG NUMBER(1) DEFAULT 0, DOC CLOB, OTHER NUMBER(1));
      ALTER TABLE E ADD CONSTRAINT CK_FLAG CHECK (FLAG IN (0,1));
      ALTER TABLE E ADD CONSTRAINT CK_DOC CHECK (DOC IS JSON);
      ALTER TABLE E ADD CONSTRAINT CK_OTHER CHECK (OTHER > 0);
    `)
    const columns = result.schema.tables[0]?.columns
    assert.deepEqual(
      columns?.map((c) => c.type.kind),
      ['boolean', 'json', 'smallint']
    )
    assert.equal(result.warnings.length, 1)
    assert.ok(result.warnings[0]?.message.includes('CHECK'))
  })
})
