import assert from 'node:assert/strict'
import { describe, it } from 'node:test'

import { oracle } from '../../../dialects/oracle.ts'
import { postgres } from '../../../dialects/postgres.ts'
import type { Schema } from '../../../schema/types.ts'
import { generateDdl } from '../../../sql/generate/generate-ddl.ts'

const schema: Schema = {
  version: 1,
  types: [
    {
      kind: 'enum',
      id: 'e1',
      name: 'order_status',
      values: ['pending', 'paid'],
    },
  ],
  tables: [
    {
      id: 'users',
      name: 'users',
      comment: 'People',
      columns: [
        {
          id: 'u1',
          name: 'id',
          type: { kind: 'integer' },
          nullable: false,
          generated: true,
        },
        {
          id: 'u2',
          name: 'email',
          type: { kind: 'varchar', length: 255 },
          nullable: false,
          comment: "the user's login",
        },
        {
          id: 'u3',
          name: 'active',
          type: { kind: 'boolean' },
          nullable: false,
          default: '1',
        },
        {
          id: 'u4',
          name: 'created_at',
          type: { kind: 'timestamp' },
          nullable: false,
          generated: true,
        },
        {
          id: 'u5',
          name: 'tags',
          type: { kind: 'array', of: { kind: 'text' } },
          nullable: true,
        },
      ],
      primaryKey: ['u1'],
      indexes: [
        {
          id: 'i1',
          name: 'uq_users_email',
          columns: ['u2'],
          unique: true,
          method: 'btree',
        },
        {
          id: 'i2',
          name: 'idx_users_tags',
          columns: ['u5'],
          unique: false,
          method: 'gin',
        },
      ],
    },
    {
      id: 'orders',
      name: 'orders',
      columns: [
        {
          id: 'o1',
          name: 'id',
          type: { kind: 'uuid' },
          nullable: false,
          generated: true,
        },
        {
          id: 'o2',
          name: 'user_id',
          type: { kind: 'integer' },
          nullable: false,
        },
        {
          id: 'o3',
          name: 'status',
          type: { kind: 'user', typeId: 'e1' },
          nullable: true,
          default: "'pending'",
        },
        { id: 'o4', name: 'payload', type: { kind: 'json' }, nullable: true },
        {
          id: 'o5',
          name: 'total',
          type: { kind: 'numeric', precision: 12, scale: 2 },
          nullable: true,
        },
      ],
      primaryKey: ['o1'],
      indexes: [
        {
          id: 'i3',
          name: 'idx_orders_user',
          columns: ['o2'],
          unique: false,
          method: 'btree',
        },
      ],
    },
  ],
  relationships: [
    {
      id: 'r1',
      from: { tableId: 'orders', columnId: 'o2' },
      to: { tableId: 'users', columnId: 'u1' },
    },
  ],
}

const EXPECTED = `CREATE TABLE USERS (
  ID NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  EMAIL VARCHAR2(255) NOT NULL,
  ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  TAGS CLOB,
  CONSTRAINT PK_USERS PRIMARY KEY (ID),
  CONSTRAINT CK_USERS_ACTIVE CHECK (ACTIVE IN (0,1)),
  CONSTRAINT CK_USERS_TAGS CHECK (TAGS IS JSON)
);

CREATE TABLE ORDERS (
  ID RAW(16) DEFAULT SYS_GUID(),
  USER_ID NUMBER(10) NOT NULL,
  STATUS VARCHAR2(7) DEFAULT 'pending',
  PAYLOAD CLOB,
  TOTAL NUMBER(12,2),
  CONSTRAINT PK_ORDERS PRIMARY KEY (ID),
  CONSTRAINT FK_ORDERS_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
  CONSTRAINT CK_ORDERS_STATUS CHECK (STATUS IN ('pending', 'paid')),
  CONSTRAINT CK_ORDERS_PAYLOAD CHECK (PAYLOAD IS JSON)
);

CREATE UNIQUE INDEX UQ_USERS_EMAIL ON USERS (EMAIL);

CREATE INDEX IDX_ORDERS_USER ON ORDERS (USER_ID);

COMMENT ON TABLE USERS IS 'People';

COMMENT ON COLUMN USERS.EMAIL IS 'the user''s login';
`

describe('generateDdl with Oracle', () => {
  const result = generateDdl(schema, oracle())

  it('writes the whole script, in the shape of the team migrations', () => {
    assert.equal(result.ok, true)
    if (result.ok) assert.equal(result.sql, EXPECTED)
  })

  it('emits no CREATE TYPE and no ALTER, and no blank line inside a statement', () => {
    assert.equal(result.ok, true)
    if (!result.ok) return
    assert.ok(!/CREATE TYPE|CREATE DOMAIN|ALTER /.test(result.sql))
    for (const statement of result.statements)
      assert.ok(!/\n\s*\n/.test(statement.sql))
    assert.deepEqual(
      result.statements.map((s) => s.kind),
      ['create', 'create', 'index', 'index', 'comment', 'comment']
    )
  })

  it('reports what it adapted, in the order it met it', () => {
    assert.equal(result.ok, true)
    if (!result.ok) return
    assert.deepEqual(
      result.notes.map((n) => [n.code, n.tableId, n.columnId ?? n.indexId]),
      [
        ['array-as-json', 'users', 'u5'],
        ['index-on-lob', 'users', 'i2'],
      ]
    )
  })

  it('uses the uuid option', () => {
    const result36 = generateDdl(schema, oracle({ uuid: 'varchar36' }))
    assert.equal(
      result36.ok &&
        result36.sql.includes('ID VARCHAR2(36) DEFAULT LOWER(REGEXP_REPLACE('),
      true
    )
  })

  it('is blocked by what Oracle refuses, with the issues', () => {
    const blocked: Schema = {
      ...schema,
      tables: [
        {
          id: 't',
          name: 'notes',
          columns: [
            { id: 'c', name: 'body', type: { kind: 'text' }, nullable: false },
          ],
          primaryKey: ['c'],
        },
      ],
      relationships: [],
      types: [],
    }
    const out = generateDdl(blocked, oracle())
    assert.equal(out.ok, false)
    if (!out.ok)
      assert.deepEqual(
        out.issues.map((i) => i.code),
        ['dialect-lob-key']
      )
    assert.equal(generateDdl(blocked, postgres).ok, true)
  })
})
