import assert from 'node:assert/strict'
import { describe, it } from 'node:test'

import { importSql } from '../../../sql/parse/import-sql.ts'

let counter = 0
const run = (sql: string, dialect: 'oracle' | 'postgres' = 'oracle') =>
  importSql(sql, () => `id-${++counter}`, dialect)

const SCRIPT = `
-- Store de identidade do CANDIDATO
CREATE TABLE KONTRATA_CANDIDATES (
  ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  NAME VARCHAR2(255),
  EMAIL VARCHAR2(255) NOT NULL,
  EMAIL_VERIFIED_AT TIMESTAMP,
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_KONTRATA_CANDIDATES PRIMARY KEY (ID),
  CONSTRAINT UQ_KONTRATA_CANDIDATES_EMAIL UNIQUE (EMAIL)
);

COMMENT ON TABLE KONTRATA_CANDIDATES IS 'Identidade do candidato';
COMMENT ON COLUMN KONTRATA_CANDIDATES.EMAIL_VERIFIED_AT IS 'Instante da confirmacao do email';

CREATE TABLE KONTRATA_JOBS (
  ID                    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  TITLE                 VARCHAR2(255)  NOT NULL,
  DESCRIPTION           CLOB,
  ADDRESS_STATE         CHAR(2)        NOT NULL,
  ADDRESS_LATITUDE      NUMBER,
  OPENINGS              NUMBER(4)      DEFAULT 1 NOT NULL,
  SALARY_MIN            NUMBER(12,2),
  PWD_ELIGIBLE          NUMBER(1)      DEFAULT 0 NOT NULL,
  STATUS                VARCHAR2(20)   DEFAULT 'DRAFT' NOT NULL,
  CONFIG                CLOB NOT NULL CHECK (CONFIG IS JSON),
  CONSTRAINT PK_KONTRATA_JOBS PRIMARY KEY (ID),
  CONSTRAINT CK_JOBS_STATUS CHECK (
    STATUS IN ('DRAFT','PUBLISHED','CLOSED')
  ),
  CONSTRAINT CK_JOBS_PWD CHECK (PWD_ELIGIBLE IN (0,1)),
  CONSTRAINT CK_JOBS_OPENINGS CHECK (OPENINGS >= 1)
);

CREATE INDEX IDX_JOBS_STATUS  ON KONTRATA_JOBS (STATUS);
CREATE INDEX IDX_JOBS_CREATED ON KONTRATA_JOBS (CREATED_AT DESC);
CREATE UNIQUE INDEX UQ_JOBS_TITLE ON KONTRATA_JOBS (TITLE);

COMMENT ON COLUMN KONTRATA_JOBS.PWD_ELIGIBLE IS '1 = vaga elegivel para pessoa com deficiencia';

CREATE TABLE KONTRATA_JOB_APPLICATIONS (
  ID               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  JOB_ID           NUMBER        NOT NULL,
  CANDIDATE_ID     NUMBER        NOT NULL,
  OUTCOME          VARCHAR2(20),
  CONSTRAINT PK_KONTRATA_JOB_APPLICATIONS PRIMARY KEY (ID),
  CONSTRAINT FK_JOB_APPLICATIONS_JOB FOREIGN KEY (JOB_ID)
    REFERENCES KONTRATA_JOBS (ID) ON DELETE CASCADE,
  CONSTRAINT FK_JOB_APPLICATIONS_CAND FOREIGN KEY (CANDIDATE_ID)
    REFERENCES KONTRATA_CANDIDATES (ID),
  CONSTRAINT UQ_JOB_APPLICATIONS UNIQUE (JOB_ID, CANDIDATE_ID),
  CONSTRAINT CK_JOB_APPL_OUTCOME CHECK (OUTCOME IN ('HIRED', 'REJECTED'))
);
`

describe('importSql in Oracle: the team migrations', () => {
  const result = run(SCRIPT)
  const table = (name: string) =>
    result.schema.tables.find((t) => t.name === name)
  const column = (t: string, c: string) =>
    table(t)?.columns.find((x) => x.name === c)

  it('has no errors, and upper-case names', () => {
    assert.deepEqual(result.errors, [])
    assert.deepEqual(
      result.schema.tables.map((t) => t.name),
      ['KONTRATA_CANDIDATES', 'KONTRATA_JOBS', 'KONTRATA_JOB_APPLICATIONS']
    )
  })

  it('reads NUMBER as number, an identity as generated, and the primary keys', () => {
    assert.deepEqual(column('KONTRATA_JOBS', 'ID')?.type, { kind: 'number' })
    assert.equal(column('KONTRATA_JOBS', 'ID')?.generated, true)
    assert.equal(
      column('KONTRATA_JOBS', 'ADDRESS_LATITUDE')?.type.kind,
      'number'
    )
    assert.deepEqual(table('KONTRATA_JOBS')?.primaryKey, [
      column('KONTRATA_JOBS', 'ID')?.id,
    ])
  })

  it('reads the other types, and the checks that make a boolean and a json', () => {
    assert.deepEqual(column('KONTRATA_JOBS', 'TITLE')?.type, {
      kind: 'varchar',
      length: 255,
    })
    assert.deepEqual(column('KONTRATA_JOBS', 'DESCRIPTION')?.type, {
      kind: 'text',
    })
    assert.deepEqual(column('KONTRATA_JOBS', 'ADDRESS_STATE')?.type, {
      kind: 'char',
      length: 2,
    })
    assert.deepEqual(column('KONTRATA_JOBS', 'OPENINGS')?.type, {
      kind: 'smallint',
    })
    assert.deepEqual(column('KONTRATA_JOBS', 'SALARY_MIN')?.type, {
      kind: 'numeric',
      precision: 12,
      scale: 2,
    })
    assert.deepEqual(column('KONTRATA_JOBS', 'PWD_ELIGIBLE')?.type, {
      kind: 'boolean',
    })
    assert.equal(column('KONTRATA_JOBS', 'PWD_ELIGIBLE')?.default, 'false')
    assert.deepEqual(column('KONTRATA_JOBS', 'CONFIG')?.type, { kind: 'json' })
    assert.deepEqual(column('KONTRATA_CANDIDATES', 'CREATED_AT')?.type, {
      kind: 'timestamp_no_tz',
    })
    assert.equal(
      column('KONTRATA_CANDIDATES', 'CREATED_AT')?.default,
      'SYSTIMESTAMP'
    )
    assert.equal(column('KONTRATA_JOBS', 'STATUS')?.default, "'DRAFT'")
    assert.equal(column('KONTRATA_JOBS', 'OPENINGS')?.default, '1')
  })

  it('reads the foreign keys, the unique constraints and indexes, and the comments', () => {
    assert.equal(result.schema.relationships.length, 2)
    const names = table('KONTRATA_JOBS')?.indexes?.map((i) => [
      i.name,
      i.unique,
      i.columns.length,
    ])
    assert.deepEqual(names, [
      ['IDX_JOBS_STATUS', false, 1],
      ['UQ_JOBS_TITLE', true, 1],
    ])
    assert.deepEqual(
      table('KONTRATA_JOB_APPLICATIONS')?.indexes?.map((i) => i.name),
      ['UQ_JOB_APPLICATIONS']
    )
    assert.equal(
      table('KONTRATA_CANDIDATES')?.comment,
      'Identidade do candidato'
    )
    assert.equal(
      column('KONTRATA_JOBS', 'PWD_ELIGIBLE')?.comment,
      '1 = vaga elegivel para pessoa com deficiencia'
    )
  })

  it('warns about what it does not model, with the line', () => {
    const text = result.warnings.map((w) => w.message).join('\n')
    for (const fragment of ['ON DELETE', 'CHECK', 'IDX_JOBS_CREATED']) {
      assert.ok(
        text.includes(fragment),
        `no warning mentions ${fragment}: ${text}`
      )
    }
    assert.ok(result.warnings.every((w) => w.line >= 1))
  })

  it('reads the same script as PostgreSQL very differently, and never as Oracle by accident', () => {
    const pg = run('CREATE TABLE a (id NUMBER)', 'postgres')
    assert.equal(pg.schema.tables[0]?.columns[0]?.type.kind, 'native')
  })
})

describe('importSql: native and number, in PostgreSQL', () => {
  it('reads bare numeric as number, and an unknown type as a native type', () => {
    const result = run(
      'CREATE TABLE t (a numeric, b decimal, c inet, d money[])',
      'postgres'
    )
    assert.deepEqual(result.warnings, [])
    const types = result.schema.tables[0]?.columns.map((c) => c.type)
    assert.deepEqual(types, [
      { kind: 'number' },
      { kind: 'number' },
      { kind: 'native', dialect: 'postgres', text: 'inet' },
      {
        kind: 'array',
        of: { kind: 'native', dialect: 'postgres', text: 'money' },
      },
    ])
  })

  it('still resolves a type the script defines', () => {
    const result = run(
      "CREATE TYPE mood AS ENUM ('a'); CREATE TABLE t (m mood, n inet);",
      'postgres'
    )
    assert.equal(result.schema.tables[0]?.columns[0]?.type.kind, 'user')
    assert.equal(result.schema.tables[0]?.columns[1]?.type.kind, 'native')
  })
})

describe('the Oracle script Forge writes reads back', () => {
  it('gives the same schema, apart from ids', async () => {
    const { generateDdl } = await import(
      '../../../sql/generate/generate-ddl.ts'
    )
    const { oracle } = await import('../../../dialects/oracle.ts')
    const first = run(SCRIPT)
    const ddl = generateDdl(first.schema, oracle())
    assert.equal(ddl.ok, true)
    if (!ddl.ok) return
    const second = run(ddl.sql)
    assert.deepEqual(second.errors, [])
    // NUMBER(5), NUMBER(10) and NUMBER(19) are what the writer gives smallint,
    // integer and bigint; read back by precision they are one size up.
    const whole = (type: { kind: string }) =>
      ['smallint', 'integer', 'bigint'].includes(type.kind)
        ? { kind: 'whole' }
        : type
    const shape = (s: typeof first.schema) =>
      s.tables.map((t) => ({
        name: t.name,
        columns: t.columns.map((c) => [
          c.name,
          whole(c.type),
          c.nullable || t.primaryKey.includes(c.id),
          c.generated ?? false,
        ]),
        indexes: (t.indexes ?? []).map((i) => [
          i.name,
          i.unique,
          i.columns.length,
        ]),
        comment: t.comment ?? null,
      }))
    assert.deepEqual(shape(second.schema), shape(first.schema))
    assert.equal(
      second.schema.relationships.length,
      first.schema.relationships.length
    )
  })
})
