import type { ColumnType } from '../schema/types.ts'
import type { Dialect } from './dialect.ts'

function typeName(type: ColumnType): string {
  switch (type.kind) {
    case 'integer':
      return 'integer'
    case 'bigint':
      return 'bigint'
    case 'text':
      return 'text'
    case 'boolean':
      return 'boolean'
    case 'uuid':
      return 'uuid'
    case 'date':
      return 'date'
    // The logical `timestamp` means an instant in time.
    case 'timestamp':
      return 'timestamptz'
    case 'json':
      return 'jsonb'
    case 'varchar':
      return `varchar(${type.length})`
    case 'numeric':
      return `numeric(${type.precision},${type.scale})`
  }
}

function quoteIdentifier(name: string): string {
  return `"${name.replaceAll('"', '""')}"`
}

function generatedClause(type: ColumnType): string | null {
  switch (type.kind) {
    case 'integer':
    case 'bigint':
      return 'GENERATED BY DEFAULT AS IDENTITY'
    case 'uuid':
      return 'DEFAULT gen_random_uuid()'
    default:
      return null
  }
}

export const postgres: Dialect = {
  id: 'postgres',
  maxIdentifierBytes: 63,
  typeName,
  generatedClause,
  quoteIdentifier,
}
