import type { Column, ColumnType, Table } from '../schema/types.ts'
import type {
  Dialect,
  IndexContext,
  TableContext,
  TableParts,
} from './dialect.ts'
import { typeSql } from './type-sql.ts'

function typeName(
  type: ColumnType,
  userTypeName: (typeId: string) => string = (typeId) => typeId
): string {
  switch (type.kind) {
    case 'integer':
      return 'integer'
    case 'bigint':
      return 'bigint'
    case 'text':
      return 'text'
    case 'boolean':
      return 'boolean'
    case 'uuid':
      return 'uuid'
    case 'date':
      return 'date'
    // The logical `timestamp` means an instant in time.
    case 'timestamp':
      return 'timestamptz'
    case 'json':
      return 'jsonb'
    case 'varchar':
      return `varchar(${type.length})`
    case 'numeric':
      return `numeric(${type.precision},${type.scale})`
    case 'smallint':
      return 'smallint'
    case 'number':
      return 'numeric'
    case 'native':
      return type.dialect === 'postgres' ? type.text : 'text'
    case 'real':
      return 'real'
    case 'double':
      return 'double precision'
    case 'time':
      return 'time'
    case 'timestamp_no_tz':
      return 'timestamp'
    case 'interval':
      return 'interval'
    case 'bytea':
      return 'bytea'
    case 'char':
      return `char(${type.length})`
    case 'array':
      return `${typeName(type.of, userTypeName)}[]`
    case 'user':
      return userTypeName(type.typeId)
  }
}

function quoteIdentifier(name: string): string {
  return `"${name.replaceAll('"', '""')}"`
}

function quoteLiteral(text: string): string {
  return `'${text.replaceAll("'", "''")}'`
}

function generatedClause(type: ColumnType): string | null {
  switch (type.kind) {
    case 'integer':
    case 'bigint':
    case 'number':
      return 'GENERATED BY DEFAULT AS IDENTITY'
    case 'uuid':
      return 'DEFAULT gen_random_uuid()'
    case 'timestamp':
      return 'DEFAULT now()'
    default:
      return null
  }
}

// An identity column is always NOT NULL in PostgreSQL; a uuid or timestamp default is not.
function generatedImpliesNotNull(type: ColumnType): boolean {
  return (
    type.kind === 'integer' || type.kind === 'bigint' || type.kind === 'number'
  )
}

const present = (text: string | undefined): text is string =>
  text !== undefined && text.trim() !== ''

function requireColumn(table: Table, columnId: string): Column {
  const found = table.columns.find((column) => column.id === columnId)
  if (!found) {
    throw new Error(`Unknown column "${columnId}" in table "${table.name}".`)
  }
  return found
}

function nativeOf(type: ColumnType): ColumnType | undefined {
  if (type.kind === 'array') return nativeOf(type.of)
  return type.kind === 'native' ? type : undefined
}

function tableParts({ schema, table, notes }: TableContext): TableParts {
  const columns = table.columns.map((column) => {
    const where = `${table.name}.${column.name}`
    const foreign = nativeOf(column.type)
    if (foreign?.kind === 'native' && foreign.dialect !== 'postgres') {
      notes.push({
        code: 'native-type',
        message: `${where}: ${foreign.text} is a ${foreign.dialect} type, so it was written as text.`,
        tableId: table.id,
        columnId: column.id,
      })
    }
    const asBigint = column.generated === true && column.type.kind === 'number'
    if (asBigint) {
      notes.push({
        code: 'identity-as-bigint',
        message: `${where}: PostgreSQL has identity only on integer types, so the generated number was written as bigint.`,
        tableId: table.id,
        columnId: column.id,
      })
    }
    // The script must say what the database will do: an identity column is
    // NOT NULL whether or not the model says so.
    const required =
      !column.nullable ||
      table.primaryKey.includes(column.id) ||
      (column.generated === true && generatedImpliesNotNull(column.type))
    const generated = column.generated ? generatedClause(column.type) : null
    const fallback =
      present(column.default) && !column.generated
        ? ` DEFAULT ${column.default}`
        : ''
    return `  ${quoteIdentifier(column.name)} ${asBigint ? 'bigint' : typeSql(schema, postgres, column.type)}${required ? ' NOT NULL' : ''}${fallback}${generated ? ` ${generated}` : ''}`
  })
  const keys =
    table.primaryKey.length > 0
      ? [
          `  PRIMARY KEY (${table.primaryKey
            .map((id) => quoteIdentifier(requireColumn(table, id).name))
            .join(', ')})`,
        ]
      : []
  return { columns, keys, checks: [] }
}

function createIndex({ table, index }: IndexContext): string {
  const columns = index.columns.map((id) =>
    quoteIdentifier(requireColumn(table, id).name)
  )
  const using = index.method === 'btree' ? '' : ` USING ${index.method}`
  return `CREATE ${index.unique ? 'UNIQUE ' : ''}INDEX ${quoteIdentifier(index.name)} ON ${quoteIdentifier(table.name)}${using} (${columns.join(', ')});`
}

export const postgres: Dialect = {
  id: 'postgres',
  supportsUserTypes: true,
  constraintName: (kind, parts) => `${kind}_${parts.join('_')}`,
  check: () => [],
  tableParts,
  createIndex,
  maxIdentifierBytes: 63,
  typeName,
  generatedClause,
  generatedImpliesNotNull,
  quoteIdentifier,
  quoteLiteral,
}
